// Fonts are self-hosted (src/styles/fonts.css, generated by `npm run fonts:build` from the languages table).
// A font not in that build yet (e.g. a language added since) is loaded from Google Fonts, once, on demand.
import selfHosted from './selfHostedFonts.json';

const requested = new Set();

export function loadFont(family) {
  if (!family || selfHosted.families.includes(family)) return;
  if (!/^[A-Za-z0-9 ]+$/.test(family) || requested.has(family)) return;
  requested.add(family);
  const base = `https://fonts.googleapis.com/css2?family=${family.trim().replace(/ +/g, '+')}`;
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  // The weight range covers the site's 300-800; a family without that axis range falls back to its default.
  link.href = `${base}:wght@300..800&display=swap`;
  link.onerror = () => {
    link.onerror = null;
    link.href = `${base}&display=swap`;
  };
  document.head.appendChild(link);
}

// CSS value for --f-lang (family names are checked above, so quoting is safe).
export function fontVar(family) {
  return family && /^[A-Za-z0-9 ]+$/.test(family) ? `"${family}"` : '';
}

// Just the glyphs of a language's switch label (Google Fonts `text=` subset, a few hundred bytes), so the
// language pill shows every label in its own script font before that language's full font is ever needed.
// The subset is renamed to labelFamily(): Google's subset CSS has no unicode-range, so under the real family
// name it would capture every character of that weight (e.g. all Open Sans 600 text) and break the page.
export function labelFamily(family) {
  return `dFresh label ${family}`;
}

export function loadLabelFont(family, text) {
  const have = selfHosted.labels[family];
  if (have && text && [...text].every((c) => have.includes(c))) return; // in fonts.css
  const key = `${family}|${text}`;
  if (!family || !text || !/^[A-Za-z0-9 ]+$/.test(family) || requested.has(key)) return;
  requested.add(key);
  const url = `https://fonts.googleapis.com/css2?family=${family.trim().replace(/ +/g, '+')}:wght@600&text=${encodeURIComponent(text)}&display=swap`;
  fetch(url)
    .then((r) => (r.ok ? r.text() : ''))
    .then((css) => {
      if (!css.includes('@font-face')) return;
      const style = document.createElement('style');
      style.textContent = css.replace(/font-family:\s*['"][^'"]*['"]/g, `font-family: '${labelFamily(family)}'`);
      document.head.appendChild(style);
    })
    .catch(() => {}); // offline: the label falls back to the full font (if loaded) or the body font
}
