-- =====================================================================
-- dFresh seed data - generated from dFresh_Website_Product_List_v0.2.xlsx
-- and the approved preview (dfresh-preview-v3.html). Do not hand-edit:
-- change the Excel / admin and re-export instead.
-- Long dashes are replaced with "-" (house style).
-- =====================================================================
USE dfresh;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO languages (lang_code, name_en, native_name, switch_label, html_lang, dir, font_family, is_default, is_active, sort_order) VALUES
  ('en', 'English', 'English', 'EN', 'en-IN', 'ltr', 'Open Sans', 1, 1, 1),
  ('ta', 'Tamil', 'தமிழ்', 'தமிழ்', 'ta-IN', 'ltr', 'Noto Sans Tamil', 0, 1, 2),
  ('hi', 'Hindi', 'हिंदी', 'हिंदी', 'hi-IN', 'ltr', 'Noto Sans Devanagari', 0, 1, 3);

INSERT INTO categories (category_key, sort_order, rep_product_id, is_active) VALUES
  ('napkins', 1, 'DZIND-DF007', 1),
  ('rolls', 2, 'DZIND-DF019', 1),
  ('kitchen', 3, 'DZIND-DF026', 1),
  ('facial', 4, 'DZIND-DF028', 1),
  ('towels', 5, 'DZIND-DF037', 1),
  ('wipes', 6, 'DZIND-DF044', 1);

INSERT INTO category_translations (category_key, lang_code, name) VALUES
  ('napkins', 'en', 'Table Napkins'),
  ('napkins', 'ta', 'டேபிள் நாப்கின்கள்'),
  ('napkins', 'hi', 'टेबल नैपकिन'),
  ('rolls', 'en', 'Toilet & Washroom Rolls'),
  ('rolls', 'ta', 'டாய்லெட் & வாஷ்ரூம் ரோல்கள்'),
  ('rolls', 'hi', 'टॉयलेट और वॉशरूम रोल'),
  ('kitchen', 'en', 'Kitchen Towels'),
  ('kitchen', 'ta', 'கிச்சன் டவல்கள்'),
  ('kitchen', 'hi', 'किचन टॉवल'),
  ('facial', 'en', 'Facial Tissue'),
  ('facial', 'ta', 'ஃபேஷியல் டிஷ்யூ'),
  ('facial', 'hi', 'फेशियल टिशू'),
  ('towels', 'en', 'Hand Towels'),
  ('towels', 'ta', 'ஹேண்ட் டவல்கள்'),
  ('towels', 'hi', 'हैंड टॉवल'),
  ('wipes', 'en', 'Wet Wipes'),
  ('wipes', 'ta', 'வெட் வைப்ஸ்'),
  ('wipes', 'hi', 'वेट वाइप्स');

INSERT INTO products (product_id, category_key, variant_of, sort_order, is_featured, featured_order, show_for_home, swatch_hex, specification, pack, spec_status, is_active) VALUES
  ('DZIND-DF001', 'napkins', NULL, 1.0, 0, NULL, 1, NULL, '1-ply · 13-15 GSM · 20×20 cm · 100 napkins', 'Pack of 100', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF002', 'napkins', NULL, 2.0, 0, NULL, 0, NULL, '1-ply · 22×22 cm · 100 napkins', 'Pack of 100', 'Supplier quote pending (RFQ) - confirm spec', 1),
  ('DZIND-DF006', 'napkins', NULL, 3.0, 0, NULL, 0, NULL, '3-ply · 27×27 cm', 'Packet (napkin count to be confirmed)', 'Pack count to confirm with supplier', 1),
  ('DZIND-DF007', 'napkins', NULL, 4.0, 1, 1, 1, NULL, '1-ply · 15-16 GSM · 30×30 cm · 100 napkins', 'Pack of 100', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF008', 'napkins', NULL, 5.0, 0, NULL, 1, '#FFFFFF', '2-ply · quarter-fold · 29×30 cm · 50 napkins', 'Pack of 50', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF013', 'napkins', NULL, 6.0, 0, NULL, 0, NULL, 'Airlaid · ~50-60 GSM · 40×40 cm · 50 napkins', 'Pack of 50', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF014', 'napkins', NULL, 7.0, 0, NULL, 0, NULL, '1-ply · L/N-fold · 20×26 cm · 100 napkins', 'Pack of 100', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF016', 'rolls', NULL, 8.0, 0, NULL, 1, NULL, '2-ply · ~300 pulls · 1 roll', '1 roll', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF017', 'rolls', NULL, 9.0, 1, 2, 1, NULL, '2-ply · 4 rolls', '4 rolls', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF018', 'rolls', NULL, 10.0, 0, NULL, 0, NULL, '2-ply · ~230 sheets per roll · 6 rolls', '6 rolls', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF019', 'rolls', NULL, 11.0, 0, NULL, 0, NULL, '2-ply · 10 rolls', '10 rolls', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF023', 'rolls', NULL, 12.0, 0, NULL, 0, NULL, '1-ply · 35+ GSM · ~175 m', '1 roll', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF024', 'rolls', NULL, 13.0, 0, NULL, 0, NULL, '1-2 ply · roll length to be confirmed', '1 roll', 'Supplier quote pending (RFQ) - confirm spec', 1),
  ('DZIND-DF025', 'kitchen', NULL, 14.0, 0, NULL, 1, NULL, '2-ply · 60 pulls · 1 roll', '1 roll', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF026', 'kitchen', NULL, 15.0, 0, NULL, 1, NULL, '2-ply · 2 × 60 pulls', '2 rolls', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF028', 'facial', NULL, 16.0, 1, 3, 1, NULL, '2-ply · ~20×20 cm · 100 pulls', 'Box of 100 pulls', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF030', 'facial', NULL, 17.0, 0, NULL, 0, NULL, '2-ply · 200 pulls', 'Box of 200 pulls', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF031', 'facial', NULL, 18.0, 0, NULL, 1, NULL, '2-ply · 200 pulls · soft pack', 'Soft pack of 200 pulls', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF035', 'facial', NULL, 19.0, 0, NULL, 0, NULL, '3-ply · 10 packs × 10 sheets', 'Multipack of 10', 'Supplier quote pending (RFQ) - confirm spec', 1),
  ('DZIND-DF048', 'facial', NULL, 20.0, 0, NULL, 1, NULL, 'Bamboo pulp · ply and pull count to be confirmed', 'Box', 'Ply and pull count to confirm with supplier', 1),
  ('DZIND-DF036', 'towels', NULL, 21.0, 0, NULL, 0, NULL, '2-ply · C-fold · 250 sheets', 'Pack of 250 sheets', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF037', 'towels', NULL, 22.0, 1, 4, 0, NULL, '1-ply · 31-35 GSM · M-fold · 150 sheets', 'Pack of 150 sheets', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF038', 'towels', NULL, 23.0, 0, NULL, 0, NULL, '2-ply · 34 GSM · V-fold · 150 sheets', 'Pack of 150 sheets', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF040', 'towels', NULL, 24.0, 0, NULL, 0, NULL, '1-2 ply · interfold (N-fold) · 100 sheets', 'Pack of 100 sheets', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF044', 'wipes', NULL, 25.0, 1, 5, 0, NULL, 'Single sachet · ~15×20 cm wipe · lemon fragrance', 'Box of 100 sachets', 'Planned spec - confirm with supplier sample', 1),
  ('DZIND-DF008-BLK', 'napkins', 'DZIND-DF008', 5.1, 0, NULL, 0, '#1B1B1D', '2-ply · quarter-fold · 29×30 cm · 50 napkins · Black', 'Pack of 50', 'Colour variant - confirm colour, shade and stock with supplier sample', 1),
  ('DZIND-DF008-BUR', 'napkins', 'DZIND-DF008', 5.2, 0, NULL, 0, '#6E1B2A', '2-ply · quarter-fold · 29×30 cm · 50 napkins · Burgundy', 'Pack of 50', 'Colour variant - confirm colour, shade and stock with supplier sample', 1),
  ('DZIND-DF008-LAV', 'napkins', 'DZIND-DF008', 5.3, 0, NULL, 0, '#B9A3DE', '2-ply · quarter-fold · 29×30 cm · 50 napkins · Lavender', 'Pack of 50', 'Colour variant - confirm colour, shade and stock with supplier sample', 1);

INSERT INTO product_translations (product_id, lang_code, name, one_liner, keywords, description, best_for, colour_name, alt_text, whatsapp_message) VALUES
  ('DZIND-DF001', 'en', 'Table Napkins 20×20', 'Everyday napkins for tea shops, eateries and homes.', '1-ply, 20×20 cm, 100 napkins, Everyday use', 'Compact 20×20 cm single-ply napkins in a handy pack of 100. Soft on the hands and easy on the budget - made for tea shops, sweet stalls, small eateries and the family dining table.', 'Tea shops · Eateries · Home', NULL, 'dFresh Table Napkins 20×20 - 1-ply · 13-15 GSM · 20×20 cm · 100 napkins', 'Hi dFresh, I''m interested in DZIND-DF001 Table Napkins 20×20 - please share price and minimum order.'),
  ('DZIND-DF001', 'ta', 'டேபிள் நாப்கின்கள் 20×20', 'டீக்கடை, சிறு உணவகங்கள் மற்றும் வீட்டுக்கான அன்றாட நாப்கின்கள்.', '1-ப்ளை, 20×20 செ.மீ, 100 நாப்கின்கள், அன்றாட பயன்பாடு', '100 நாப்கின்கள் கொண்ட வசதியான பேக்கில் 20×20 செ.மீ அளவுள்ள ஒற்றை-ப்ளை நாப்கின்கள். கைகளுக்கு மென்மையானவை, பட்ஜெட்டுக்கு ஏற்றவை - டீக்கடைகள், இனிப்புக் கடைகள், சிறு உணவகங்கள் மற்றும் வீட்டு உணவு மேசைக்காக.', 'டீக்கடைகள் · உணவகங்கள் · வீடு', NULL, NULL, NULL),
  ('DZIND-DF001', 'hi', 'टेबल नैपकिन 20×20', 'चाय की दुकानों, छोटे भोजनालयों और घरों के लिए रोज़मर्रा के नैपकिन।', '1-प्लाई, 20×20 सेमी, 100 नैपकिन, रोज़ाना उपयोग', '100 नैपकिन के सुविधाजनक पैक में 20×20 सेमी के सिंगल-प्लाई नैपकिन। हाथों पर मुलायम और बजट के अनुकूल - चाय की दुकानों, मिठाई की दुकानों, छोटे भोजनालयों और घर की डाइनिंग टेबल के लिए।', 'चाय की दुकानें · भोजनालय · घर', NULL, NULL, NULL),
  ('DZIND-DF002', 'en', 'Restaurant Napkins 22×22', 'Value napkins sized for restaurants and canteens.', '1-ply, 22×22 cm, 100 napkins, Bulk supply', 'A 22×22 cm single-ply napkin made for busy restaurants, canteens, messes and caterers. Supplied in packs of 100 with regular delivery, so your tables never run short.', 'Restaurants · Canteens · Caterers', NULL, 'dFresh Restaurant Napkins 22×22 - 1-ply · 22×22 cm · 100 napkins', 'Hi dFresh, I''m interested in DZIND-DF002 Restaurant Napkins 22×22 - please share price and minimum order.'),
  ('DZIND-DF002', 'ta', 'உணவக நாப்கின்கள் 22×22', 'உணவகங்கள் மற்றும் கேன்டீன்களுக்கு ஏற்ற அளவிலான சிக்கனமான நாப்கின்கள்.', '1-ப்ளை, 22×22 செ.மீ, 100 நாப்கின்கள், மொத்த சப்ளை', 'பரபரப்பான உணவகங்கள், கேன்டீன்கள், மெஸ்கள் மற்றும் கேட்டரர்களுக்காக உருவாக்கப்பட்ட 22×22 செ.மீ ஒற்றை-ப்ளை நாப்கின். 100 நாப்கின் பேக்குகளில் தொடர்ந்த டெலிவரியுடன் - உங்கள் மேசைகளில் குறைவு ஏற்படாது.', 'உணவகங்கள் · கேன்டீன்கள் · கேட்டரர்கள்', NULL, NULL, NULL),
  ('DZIND-DF002', 'hi', 'रेस्टोरेंट नैपकिन 22×22', 'रेस्टोरेंट और कैंटीन के लिए सही आकार के किफ़ायती नैपकिन।', '1-प्लाई, 22×22 सेमी, 100 नैपकिन, थोक आपूर्ति', 'व्यस्त रेस्टोरेंट, कैंटीन, मेस और कैटरर्स के लिए बना 22×22 सेमी का सिंगल-प्लाई नैपकिन। 100 नैपकिन के पैक में नियमित डिलीवरी के साथ - आपकी टेबल पर कभी कमी नहीं होगी।', 'रेस्टोरेंट · कैंटीन · कैटरर्स', NULL, NULL, NULL),
  ('DZIND-DF006', 'en', 'Premium 3-ply Napkins 27×27', 'Thick 3-ply napkins for fine dining and hotels.', '3-ply, 27×27 cm, Premium, Hotels', 'Three layers for a fuller, softer feel on the table. Our 27×27 cm premium napkin suits hotel restaurants, banquet halls and fine-dining tables where presentation matters.', 'Hotels · Banquet halls · Fine dining', NULL, 'dFresh Premium 3-ply Napkins 27×27 - 3-ply · 27×27 cm', 'Hi dFresh, I''m interested in DZIND-DF006 Premium 3-ply Napkins 27×27 - please share price and minimum order.'),
  ('DZIND-DF006', 'ta', 'பிரீமியம் 3-ப்ளை நாப்கின்கள் 27×27', 'ஃபைன் டைனிங் மற்றும் ஹோட்டல்களுக்கான தடிமனான 3-ப்ளை நாப்கின்கள்.', '3-ப்ளை, 27×27 செ.மீ, பிரீமியம், ஹோட்டல்கள்', 'மேசையில் கூடுதல் மென்மையும் தடிமனும் தரும் மூன்று அடுக்குகள். எங்கள் 27×27 செ.மீ பிரீமியம் நாப்கின், தோற்றம் முக்கியமான ஹோட்டல் உணவகங்கள், விருந்து அரங்குகள் மற்றும் ஃபைன் டைனிங் மேசைகளுக்கு ஏற்றது.', 'ஹோட்டல்கள் · விருந்து அரங்குகள் · ஃபைன் டைனிங்', NULL, NULL, NULL),
  ('DZIND-DF006', 'hi', 'प्रीमियम 3-प्लाई नैपकिन 27×27', 'फाइन डाइनिंग और होटलों के लिए मोटे 3-प्लाई नैपकिन।', '3-प्लाई, 27×27 सेमी, प्रीमियम, होटल', 'तीन परतें, टेबल पर ज़्यादा भरा-भरा और मुलायम एहसास। हमारा 27×27 सेमी प्रीमियम नैपकिन होटल रेस्टोरेंट, बैंक्वेट हॉल और फाइन-डाइनिंग टेबल के लिए उपयुक्त है, जहाँ प्रस्तुति मायने रखती है।', 'होटल · बैंक्वेट हॉल · फाइन डाइनिंग', NULL, NULL, NULL),
  ('DZIND-DF007', 'en', 'Table Napkins 30×30', 'The everyday full-size napkin - soft, 30×30 cm, 100 per pack.', '1-ply, 30×30 cm, 100 napkins, Home & restaurants', 'The size restaurants and homes reach for most. A full 30×30 cm single-ply napkin (15-16 GSM) in a pack of 100 - ready for dining tables, takeaway counters, parties and everyday meals.', 'Home · Restaurants · Parties', NULL, 'dFresh Table Napkins 30×30 - 1-ply · 15-16 GSM · 30×30 cm · 100 napkins', 'Hi dFresh, I''m interested in DZIND-DF007 Table Napkins 30×30 - please share price and minimum order.'),
  ('DZIND-DF007', 'ta', 'டேபிள் நாப்கின்கள் 30×30', 'அன்றாட முழு அளவு நாப்கின் - மென்மையானது, 30×30 செ.மீ, ஒரு பேக்கில் 100.', '1-ப்ளை, 30×30 செ.மீ, 100 நாப்கின்கள், வீடு & உணவகங்கள்', 'உணவகங்களும் வீடுகளும் அதிகம் விரும்பும் அளவு. 100 நாப்கின் பேக்கில் முழு 30×30 செ.மீ ஒற்றை-ப்ளை நாப்கின் (15-16 GSM) - உணவு மேசைகள், டேக்அவே கவுண்டர்கள், விருந்துகள் மற்றும் அன்றாட உணவுக்குத் தயார்.', 'வீடு · உணவகங்கள் · விருந்துகள்', NULL, NULL, NULL),
  ('DZIND-DF007', 'hi', 'टेबल नैपकिन 30×30', 'रोज़ाना का पूरे आकार का नैपकिन - मुलायम, 30×30 सेमी, एक पैक में 100।', '1-प्लाई, 30×30 सेमी, 100 नैपकिन, घर और रेस्टोरेंट', 'वह आकार जो रेस्टोरेंट और घर सबसे ज़्यादा पसंद करते हैं। 100 के पैक में पूरा 30×30 सेमी सिंगल-प्लाई नैपकिन (15-16 GSM) - डाइनिंग टेबल, टेकअवे काउंटर, पार्टियों और रोज़ के भोजन के लिए तैयार।', 'घर · रेस्टोरेंट · पार्टियाँ', NULL, NULL, NULL),
  ('DZIND-DF008', 'en', '2-ply Napkins 29×30', 'Double-layer napkins for a softer, stronger wipe.', '2-ply, 29×30 cm, Quarter-fold, 50 napkins', 'Two plies, quarter-folded, 29×30 cm. A step up from everyday napkins for family restaurants, cafés and home dinners - neat on the table and comfortable in the hand. Pack of 50.', 'Cafés · Family restaurants · Home', 'White', 'dFresh 2-ply Napkins 29×30 - 2-ply · quarter-fold · 29×30 cm · 50 napkins', 'Hi dFresh, I''m interested in DZIND-DF008 2-ply Napkins 29×30 - please share price and minimum order.'),
  ('DZIND-DF008', 'ta', '2-ப்ளை நாப்கின்கள் 29×30', 'கூடுதல் மென்மை மற்றும் வலிமைக்கு இரட்டை அடுக்கு நாப்கின்கள்.', '2-ப்ளை, 29×30 செ.மீ, கால்-மடிப்பு, 50 நாப்கின்கள்', 'இரண்டு அடுக்குகள், கால்-மடிப்பு, 29×30 செ.மீ. குடும்ப உணவகங்கள், கஃபேக்கள் மற்றும் வீட்டு விருந்துகளுக்கு அன்றாட நாப்கினை விட ஒரு படி மேல் - மேசையில் நேர்த்தியாகவும் கையில் வசதியாகவும். 50 நாப்கின் பேக்.', 'கஃபேக்கள் · குடும்ப உணவகங்கள் · வீடு', 'வெள்ளை', NULL, NULL),
  ('DZIND-DF008', 'hi', '2-प्लाई नैपकिन 29×30', 'ज़्यादा मुलायम और मज़बूत पोंछने के लिए दोहरी परत वाले नैपकिन।', '2-प्लाई, 29×30 सेमी, क्वार्टर-फोल्ड, 50 नैपकिन', 'दो परतें, क्वार्टर-फोल्ड, 29×30 सेमी। फैमिली रेस्टोरेंट, कैफ़े और घर के डिनर के लिए रोज़ के नैपकिन से एक कदम आगे - टेबल पर सुघड़ और हाथ में आरामदायक। 50 का पैक।', 'कैफ़े · फैमिली रेस्टोरेंट · घर', 'सफ़ेद', NULL, NULL),
  ('DZIND-DF008-BLK', 'en', '2-ply Napkins 29×30 - Black', 'Bold black 2-ply napkins for a striking table.', '2-ply, 29×30 cm, Quarter-fold, 50 napkins, Black', 'The same 2-ply, quarter-folded 29×30 cm napkin in deep black. Made for cafés, bars, themed events and modern restaurant tables where white napkins look too plain. Pack of 50.', 'Cafés · Bars · Themed events', 'Black', 'dFresh 2-ply Napkins 29×30, Black - 2-ply · quarter-fold · 29×30 cm · 50 napkins', 'Hi dFresh, I''m interested in DZIND-DF008-BLK 2-ply Napkins 29×30 (Black) - please share price and minimum order.'),
  ('DZIND-DF008-BLK', 'ta', '2-ப்ளை நாப்கின்கள் 29×30 - கருப்பு', 'கவர்ச்சியான மேசைக்கு கருப்பு நிற 2-ப்ளை நாப்கின்கள்.', '2-ப்ளை, 29×30 செ.மீ, கால்-மடிப்பு, 50 நாப்கின்கள், கருப்பு', 'அதே 2-ப்ளை, கால்-மடிப்பு, 29×30 செ.மீ நாப்கின் - அடர் கருப்பு நிறத்தில். வெள்ளை நாப்கின் சாதாரணமாகத் தோன்றும் கஃபேக்கள், பார்கள், தீம் நிகழ்வுகள் மற்றும் நவீன உணவக மேசைகளுக்காக. 50 நாப்கின் பேக்.', 'கஃபேக்கள் · பார்கள் · தீம் நிகழ்வுகள்', 'கருப்பு', NULL, NULL),
  ('DZIND-DF008-BLK', 'hi', '2-प्लाई नैपकिन 29×30 - काला', 'आकर्षक टेबल के लिए काले रंग के 2-प्लाई नैपकिन।', '2-प्लाई, 29×30 सेमी, क्वार्टर-फोल्ड, 50 नैपकिन, काला', 'वही 2-प्लाई, क्वार्टर-फोल्ड, 29×30 सेमी नैपकिन - गहरे काले रंग में। कैफ़े, बार, थीम इवेंट और आधुनिक रेस्टोरेंट टेबल के लिए, जहाँ सफ़ेद नैपकिन बहुत सादे लगते हैं। 50 का पैक।', 'कैफ़े · बार · थीम इवेंट', 'काला', NULL, NULL),
  ('DZIND-DF008-BUR', 'en', '2-ply Napkins 29×30 - Burgundy', 'Rich burgundy 2-ply napkins for festive and fine dining.', '2-ply, 29×30 cm, Quarter-fold, 50 napkins, Burgundy', 'The same 2-ply, quarter-folded 29×30 cm napkin in rich burgundy. A warm, festive touch for weddings, receptions, fine-dining tables and festival dinners. Pack of 50.', 'Weddings · Fine dining · Festivals', 'Burgundy', 'dFresh 2-ply Napkins 29×30, Burgundy - 2-ply · quarter-fold · 29×30 cm · 50 napkins', 'Hi dFresh, I''m interested in DZIND-DF008-BUR 2-ply Napkins 29×30 (Burgundy) - please share price and minimum order.'),
  ('DZIND-DF008-BUR', 'ta', '2-ப்ளை நாப்கின்கள் 29×30 - பர்கண்டி', 'பண்டிகை மற்றும் ஃபைன்-டைனிங் விருந்துகளுக்கு பர்கண்டி நிற 2-ப்ளை நாப்கின்கள்.', '2-ப்ளை, 29×30 செ.மீ, கால்-மடிப்பு, 50 நாப்கின்கள், பர்கண்டி', 'அதே 2-ப்ளை, கால்-மடிப்பு, 29×30 செ.மீ நாப்கின் - செழுமையான பர்கண்டி நிறத்தில். திருமணங்கள், வரவேற்புகள், ஃபைன்-டைனிங் மேசைகள் மற்றும் பண்டிகை விருந்துகளுக்கு இதமான, கொண்டாட்டத் தோற்றம். 50 நாப்கின் பேக்.', 'திருமணங்கள் · ஃபைன் டைனிங் · பண்டிகைகள்', 'பர்கண்டி', NULL, NULL),
  ('DZIND-DF008-BUR', 'hi', '2-प्लाई नैपकिन 29×30 - बरगंडी', 'उत्सव और फाइन डाइनिंग के लिए बरगंडी रंग के 2-प्लाई नैपकिन।', '2-प्लाई, 29×30 सेमी, क्वार्टर-फोल्ड, 50 नैपकिन, बरगंडी', 'वही 2-प्लाई, क्वार्टर-फोल्ड, 29×30 सेमी नैपकिन - गहरे बरगंडी रंग में। शादी, रिसेप्शन, फाइन-डाइनिंग टेबल और त्योहार के खाने के लिए एक गर्मजोशी भरा, उत्सव जैसा स्पर्श। 50 का पैक।', 'शादियाँ · फाइन डाइनिंग · त्योहार', 'बरगंडी', NULL, NULL),
  ('DZIND-DF008-LAV', 'en', '2-ply Napkins 29×30 - Lavender', 'Soft lavender 2-ply napkins for parties and celebrations.', '2-ply, 29×30 cm, Quarter-fold, 50 napkins, Lavender', 'The same 2-ply, quarter-folded 29×30 cm napkin in soft lavender. Pretty on the table for birthdays, baby showers, parties and cafés. Pack of 50.', 'Parties · Baby showers · Cafés', 'Lavender', 'dFresh 2-ply Napkins 29×30, Lavender - 2-ply · quarter-fold · 29×30 cm · 50 napkins', 'Hi dFresh, I''m interested in DZIND-DF008-LAV 2-ply Napkins 29×30 (Lavender) - please share price and minimum order.'),
  ('DZIND-DF008-LAV', 'ta', '2-ப்ளை நாப்கின்கள் 29×30 - லாவெண்டர்', 'பார்ட்டிகள் மற்றும் கொண்டாட்டங்களுக்கு மென்மையான லாவெண்டர் நிற 2-ப்ளை நாப்கின்கள்.', '2-ப்ளை, 29×30 செ.மீ, கால்-மடிப்பு, 50 நாப்கின்கள், லாவெண்டர்', 'அதே 2-ப்ளை, கால்-மடிப்பு, 29×30 செ.மீ நாப்கின் - மென்மையான லாவெண்டர் நிறத்தில். பிறந்தநாள், வளைகாப்பு, பார்ட்டிகள் மற்றும் கஃபேக்களில் மேசைக்கு அழகு சேர்க்கும். 50 நாப்கின் பேக்.', 'பார்ட்டிகள் · வளைகாப்பு · கஃபேக்கள்', 'லாவெண்டர்', NULL, NULL),
  ('DZIND-DF008-LAV', 'hi', '2-प्लाई नैपकिन 29×30 - लैवेंडर', 'पार्टियों और समारोहों के लिए हल्के लैवेंडर रंग के 2-प्लाई नैपकिन।', '2-प्लाई, 29×30 सेमी, क्वार्टर-फोल्ड, 50 नैपकिन, लैवेंडर', 'वही 2-प्लाई, क्वार्टर-फोल्ड, 29×30 सेमी नैपकिन - हल्के लैवेंडर रंग में। जन्मदिन, गोद भराई, पार्टियों और कैफ़े में टेबल को सुंदर बनाते हैं। 50 का पैक।', 'पार्टियाँ · गोद भराई · कैफ़े', 'लैवेंडर', NULL, NULL),
  ('DZIND-DF013', 'en', 'Airlaid Dinner Napkins 40×40', 'Cloth-like airlaid napkins for weddings and banquets.', 'Airlaid, 40×40 cm, Cloth-like, 50 napkins', 'Airlaid napkins (about 50-60 GSM) feel and fold like cloth, without the washing. The large 40×40 cm size dresses up wedding tables, banquets and premium hotel dining. Pack of 50.', 'Weddings · Banquets · Premium hotels', NULL, 'dFresh Airlaid Dinner Napkins 40×40 - Airlaid · ~50-60 GSM · 40×40 cm · 50 napkins', 'Hi dFresh, I''m interested in DZIND-DF013 Airlaid Dinner Napkins 40×40 - please share price and minimum order.'),
  ('DZIND-DF013', 'ta', 'ஏர்லெய்டு டின்னர் நாப்கின்கள் 40×40', 'திருமணங்கள் மற்றும் விருந்துகளுக்கு துணி போன்ற ஏர்லெய்டு நாப்கின்கள்.', 'ஏர்லெய்டு, 40×40 செ.மீ, துணி போன்றது, 50 நாப்கின்கள்', 'ஏர்லெய்டு நாப்கின்கள் (சுமார் 50-60 GSM) துணியைப் போலவே உணரப்படும், மடிக்கப்படும் - துவைக்க வேண்டியதில்லை. பெரிய 40×40 செ.மீ அளவு திருமண மேசைகள், விருந்துகள் மற்றும் பிரீமியம் ஹோட்டல் உணவுக்கு அழகு சேர்க்கும். 50 நாப்கின் பேக்.', 'திருமணங்கள் · விருந்துகள் · பிரீமியம் ஹோட்டல்கள்', NULL, NULL, NULL),
  ('DZIND-DF013', 'hi', 'एयरलेड डिनर नैपकिन 40×40', 'शादियों और भोज के लिए कपड़े जैसे एयरलेड नैपकिन।', 'एयरलेड, 40×40 सेमी, कपड़े जैसा, 50 नैपकिन', 'एयरलेड नैपकिन (लगभग 50-60 GSM) कपड़े जैसे महसूस होते हैं और वैसे ही मुड़ते हैं - धोने की ज़रूरत नहीं। बड़ा 40×40 सेमी आकार शादी की टेबल, भोज और प्रीमियम होटल डाइनिंग को सजाता है। 50 का पैक।', 'शादियाँ · भोज · प्रीमियम होटल', NULL, NULL, NULL),
  ('DZIND-DF014', 'en', 'Dispenser Napkins', 'Interfolded napkins for counter and table dispensers.', 'Dispenser, L/N-fold, 20×26 cm, 100 napkins', 'One napkin at a time helps cut waste at busy counters. Folded 20×26 cm napkins for standard tabletop and counter dispensers in quick-service restaurants, bakeries, juice shops and cafés. Pack of 100.', 'Quick-service restaurants · Bakeries · Cafés', NULL, 'dFresh Dispenser Napkins - 1-ply · L/N-fold · 20×26 cm · 100 napkins', 'Hi dFresh, I''m interested in DZIND-DF014 Dispenser Napkins - please share price and minimum order.'),
  ('DZIND-DF014', 'ta', 'டிஸ்பென்சர் நாப்கின்கள்', 'கவுண்டர் மற்றும் மேசை டிஸ்பென்சர்களுக்கான இன்டர்ஃபோல்டு நாப்கின்கள்.', 'டிஸ்பென்சர், L/N-மடிப்பு, 20×26 செ.மீ, 100 நாப்கின்கள்', 'ஒரு முறைக்கு ஒரு நாப்கின் - பரபரப்பான கவுண்டர்களில் வீணாவதைக் குறைக்க உதவும். குயிக்-சர்வீஸ் உணவகங்கள், பேக்கரிகள், ஜூஸ் கடைகள் மற்றும் கஃபேக்களில் உள்ள டேபிள்டாப், கவுண்டர் டிஸ்பென்சர்களுக்கான 20×26 செ.மீ மடிப்பு நாப்கின்கள். 100 நாப்கின் பேக்.', 'குயிக்-சர்வீஸ் உணவகங்கள் · பேக்கரிகள் · கஃபேக்கள்', NULL, NULL, NULL),
  ('DZIND-DF014', 'hi', 'डिस्पेंसर नैपकिन', 'काउंटर और टेबल डिस्पेंसर के लिए इंटरफोल्ड नैपकिन।', 'डिस्पेंसर, L/N-फोल्ड, 20×26 सेमी, 100 नैपकिन', 'एक बार में एक नैपकिन - व्यस्त काउंटर पर बर्बादी कम करने में मदद। क्विक-सर्विस रेस्टोरेंट, बेकरी, जूस की दुकानों और कैफ़े के टेबलटॉप व काउंटर डिस्पेंसर के लिए 20×26 सेमी फोल्डेड नैपकिन। 100 का पैक।', 'क्विक-सर्विस रेस्टोरेंट · बेकरी · कैफ़े', NULL, NULL, NULL),
  ('DZIND-DF016', 'en', 'Toilet Roll', 'Soft 2-ply toilet roll with around 300 pulls.', '2-ply, ~300 pulls, Single roll, Home', 'A soft, two-ply toilet roll with about 300 pulls - sold singly so shops can offer an easy everyday buy. Perforated for clean tearing and wound on a standard core to fit regular holders.', 'Home · Shops · Medical shops', NULL, 'dFresh Toilet Roll - 2-ply · ~300 pulls · 1 roll', 'Hi dFresh, I''m interested in DZIND-DF016 Toilet Roll - please share price and minimum order.'),
  ('DZIND-DF016', 'ta', 'டாய்லெட் ரோல்', 'சுமார் 300 ஷீட்கள் கொண்ட மென்மையான 2-ப்ளை டாய்லெட் ரோல்.', '2-ப்ளை, ~300 ஷீட்கள், ஒற்றை ரோல், வீடு', 'சுமார் 300 ஷீட்கள் கொண்ட மென்மையான இரட்டை அடுக்கு டாய்லெட் ரோல் - கடைகள் எளிதாக விற்க தனித்தனியாகக் கிடைக்கிறது. சுத்தமாகக் கிழிக்க துளையிடப்பட்டது, வழக்கமான ஹோல்டர்களில் பொருந்தும் நிலையான கோர் கொண்டது.', 'வீடு · கடைகள் · மருந்தகங்கள்', NULL, NULL, NULL),
  ('DZIND-DF016', 'hi', 'टॉयलेट रोल', 'लगभग 300 शीट वाला मुलायम 2-प्लाई टॉयलेट रोल।', '2-प्लाई, ~300 शीट, सिंगल रोल, घर', 'लगभग 300 शीट वाला मुलायम दो-प्लाई टॉयलेट रोल - अकेले भी उपलब्ध, ताकि दुकानें रोज़ की आसान खरीद दे सकें। साफ़ फाड़ने के लिए छिद्रित, सामान्य होल्डर में फिट होने वाले स्टैंडर्ड कोर पर।', 'घर · दुकानें · मेडिकल स्टोर', NULL, NULL, NULL),
  ('DZIND-DF017', 'en', 'Toilet Rolls - 4 Pack', 'Family pack of four soft 2-ply rolls.', '2-ply, 4 rolls, Family pack, Value', 'Four soft two-ply toilet rolls in one wrapped pack - the everyday choice for homes, hostels and small offices. Same quality as our single roll, better value per roll.', 'Home · Hostels · Small offices', NULL, 'dFresh Toilet Rolls - 4 Pack - 2-ply · 4 rolls', 'Hi dFresh, I''m interested in DZIND-DF017 Toilet Rolls - 4 Pack - please share price and minimum order.'),
  ('DZIND-DF017', 'ta', 'டாய்லெட் ரோல்கள் - 4 பேக்', 'நான்கு மென்மையான 2-ப்ளை ரோல்கள் கொண்ட குடும்ப பேக்.', '2-ப்ளை, 4 ரோல்கள், குடும்ப பேக், சிக்கனம்', 'ஒரே பேக்கில் நான்கு மென்மையான இரட்டை அடுக்கு டாய்லெட் ரோல்கள் - வீடுகள், விடுதிகள் மற்றும் சிறு அலுவலகங்களுக்கான அன்றாடத் தேர்வு. எங்கள் ஒற்றை ரோலின் அதே தரம், ஒரு ரோலுக்கு குறைந்த விலை.', 'வீடு · விடுதிகள் · சிறு அலுவலகங்கள்', NULL, NULL, NULL),
  ('DZIND-DF017', 'hi', 'टॉयलेट रोल - 4 पैक', 'चार मुलायम 2-प्लाई रोल का फैमिली पैक।', '2-प्लाई, 4 रोल, फैमिली पैक, किफ़ायती', 'एक पैक में चार मुलायम दो-प्लाई टॉयलेट रोल - घरों, हॉस्टल और छोटे दफ़्तरों की रोज़ की पसंद। हमारे सिंगल रोल जैसी ही गुणवत्ता, प्रति रोल बेहतर कीमत।', 'घर · हॉस्टल · छोटे दफ़्तर', NULL, NULL, NULL),
  ('DZIND-DF018', 'en', 'Toilet Rolls - 6 Pack', 'Six-roll pack for bigger homes and guest houses.', '2-ply, 6 rolls, ~230 sheets, Stock-up', 'Six soft two-ply rolls (about 230 sheets each) for larger families, guest houses and service apartments. Stock up once, worry less.', 'Large families · Guest houses · Service apartments', NULL, 'dFresh Toilet Rolls - 6 Pack - 2-ply · ~230 sheets per roll · 6 rolls', 'Hi dFresh, I''m interested in DZIND-DF018 Toilet Rolls - 6 Pack - please share price and minimum order.'),
  ('DZIND-DF018', 'ta', 'டாய்லெட் ரோல்கள் - 6 பேக்', 'பெரிய வீடுகள் மற்றும் விருந்தினர் இல்லங்களுக்கான ஆறு ரோல் பேக்.', '2-ப்ளை, 6 ரோல்கள், ~230 ஷீட்கள், சேமிப்பு', 'பெரிய குடும்பங்கள், விருந்தினர் இல்லங்கள் மற்றும் சர்வீஸ் அபார்ட்மென்ட்களுக்கு ஆறு மென்மையான இரட்டை அடுக்கு ரோல்கள் (ஒவ்வொன்றிலும் சுமார் 230 ஷீட்கள்). ஒருமுறை வாங்கி வைத்தால் கவலை குறைவு.', 'பெரிய குடும்பங்கள் · விருந்தினர் இல்லங்கள் · சர்வீஸ் அபார்ட்மென்ட்கள்', NULL, NULL, NULL),
  ('DZIND-DF018', 'hi', 'टॉयलेट रोल - 6 पैक', 'बड़े घरों और गेस्ट हाउस के लिए छह रोल का पैक।', '2-प्लाई, 6 रोल, ~230 शीट, स्टॉक-अप', 'बड़े परिवारों, गेस्ट हाउस और सर्विस अपार्टमेंट के लिए छह मुलायम दो-प्लाई रोल (हर रोल में लगभग 230 शीट)। एक बार स्टॉक करें, चिंता कम करें।', 'बड़े परिवार · गेस्ट हाउस · सर्विस अपार्टमेंट', NULL, NULL, NULL),
  ('DZIND-DF019', 'en', 'Toilet Rolls - 10 Pack', 'Bulk 10-roll pack for offices, hostels and lodges.', '2-ply, 10 rolls, Bulk pack, Institutions', 'Ten two-ply rolls in one pack for offices, hostels, lodges and clinics that need a steady supply. Fewer re-orders, easier storage.', 'Offices · Hostels · Lodges', NULL, 'dFresh Toilet Rolls - 10 Pack - 2-ply · 10 rolls', 'Hi dFresh, I''m interested in DZIND-DF019 Toilet Rolls - 10 Pack - please share price and minimum order.'),
  ('DZIND-DF019', 'ta', 'டாய்லெட் ரோல்கள் - 10 பேக்', 'அலுவலகங்கள், விடுதிகள் மற்றும் லாட்ஜ்களுக்கான 10 ரோல் மொத்த பேக்.', '2-ப்ளை, 10 ரோல்கள், மொத்த பேக், நிறுவனங்கள்', 'தொடர்ந்த சப்ளை தேவைப்படும் அலுவலகங்கள், விடுதிகள், லாட்ஜ்கள் மற்றும் கிளினிக்குகளுக்கு ஒரே பேக்கில் பத்து இரட்டை அடுக்கு ரோல்கள். குறைவான மறு-ஆர்டர்கள், எளிதான சேமிப்பு.', 'அலுவலகங்கள் · விடுதிகள் · லாட்ஜ்கள்', NULL, NULL, NULL),
  ('DZIND-DF019', 'hi', 'टॉयलेट रोल - 10 पैक', 'दफ़्तरों, हॉस्टल और लॉज के लिए 10 रोल का बल्क पैक।', '2-प्लाई, 10 रोल, बल्क पैक, संस्थान', 'लगातार आपूर्ति चाहने वाले दफ़्तरों, हॉस्टल, लॉज और क्लिनिक के लिए एक पैक में दस दो-प्लाई रोल। कम री-ऑर्डर, आसान भंडारण।', 'दफ़्तर · हॉस्टल · लॉज', NULL, NULL, NULL),
  ('DZIND-DF023', 'en', 'Hand Roll Towel', 'Long hand-towel roll for washroom roll dispensers.', 'Hand towel roll, ~175 m, 35+ GSM, Dispenser', 'A heavy single-ply paper towel roll of about 175 metres (35+ GSM) for hand-towel roll dispensers in office, mall, hospital and factory washrooms. A long roll means fewer refills for your housekeeping team.', 'Offices · Malls · Hospitals · Factories', NULL, 'dFresh Hand Roll Towel - 1-ply · 35+ GSM · ~175 m', 'Hi dFresh, I''m interested in DZIND-DF023 Hand Roll Towel - please share price and minimum order.'),
  ('DZIND-DF023', 'ta', 'ஹேண்ட் ரோல் டவல்', 'வாஷ்ரூம் ரோல் டிஸ்பென்சர்களுக்கான நீண்ட ஹேண்ட் டவல் ரோல்.', 'ஹேண்ட் டவல் ரோல், ~175 மீ, 35+ GSM, டிஸ்பென்சர்', 'அலுவலகம், மால், மருத்துவமனை மற்றும் தொழிற்சாலை வாஷ்ரூம்களில் உள்ள ஹேண்ட் டவல் ரோல் டிஸ்பென்சர்களுக்கான சுமார் 175 மீட்டர் (35+ GSM) தடிமனான ஒற்றை-ப்ளை பேப்பர் டவல் ரோல். நீண்ட ரோல் என்பதால் உங்கள் ஹவுஸ்கீப்பிங் குழு குறைவாக நிரப்பினால் போதும்.', 'அலுவலகங்கள் · மால்கள் · மருத்துவமனைகள் · தொழிற்சாலைகள்', NULL, NULL, NULL),
  ('DZIND-DF023', 'hi', 'हैंड रोल टॉवल', 'वॉशरूम रोल डिस्पेंसर के लिए लंबा हैंड टॉवल रोल।', 'हैंड टॉवल रोल, ~175 मी, 35+ GSM, डिस्पेंसर', 'दफ़्तर, मॉल, अस्पताल और फ़ैक्टरी के वॉशरूम में हैंड-टॉवल रोल डिस्पेंसर के लिए लगभग 175 मीटर (35+ GSM) का मोटा सिंगल-प्लाई पेपर टॉवल रोल। लंबा रोल यानी आपकी हाउसकीपिंग टीम को कम बार भरना पड़ता है।', 'दफ़्तर · मॉल · अस्पताल · फ़ैक्टरियाँ', NULL, NULL, NULL),
  ('DZIND-DF024', 'en', 'Centre-pull Roll', 'Pull-from-the-centre roll for clean, one-hand use.', 'Centre-pull, 1-2 ply, Dispenser, Touch-less pull', 'Sheets pull from the centre of the roll, so users touch only what they take. Fits centre-pull dispensers in kitchens, hospital wards, workshops and food-processing areas.', 'Kitchens · Hospitals · Workshops', NULL, 'dFresh Centre-pull Roll - 1-2 ply · roll length to be confirmed', 'Hi dFresh, I''m interested in DZIND-DF024 Centre-pull Roll - please share price and minimum order.'),
  ('DZIND-DF024', 'ta', 'சென்டர்-புல் ரோல்', 'ஒரு கையால் சுத்தமாக எடுக்க நடுவிலிருந்து இழுக்கும் ரோல்.', 'சென்டர்-புல், 1-2 ப்ளை, டிஸ்பென்சர், எளிதான இழுப்பு', 'ரோலின் நடுவிலிருந்து ஷீட்கள் வெளிவருவதால், பயனர்கள் தாங்கள் எடுப்பதை மட்டுமே தொடுவார்கள். சமையலறைகள், மருத்துவமனை வார்டுகள், பணிமனைகள் மற்றும் உணவு பதப்படுத்தும் இடங்களில் உள்ள சென்டர்-புல் டிஸ்பென்சர்களுக்கு ஏற்றது.', 'சமையலறைகள் · மருத்துவமனைகள் · பணிமனைகள்', NULL, NULL, NULL),
  ('DZIND-DF024', 'hi', 'सेंटर-पुल रोल', 'एक हाथ से साफ़ इस्तेमाल के लिए बीच से खींचने वाला रोल।', 'सेंटर-पुल, 1-2 प्लाई, डिस्पेंसर, आसान खिंचाव', 'शीट रोल के बीच से निकलती हैं, इसलिए उपयोगकर्ता केवल वही छूते हैं जो वे लेते हैं। रसोई, अस्पताल वार्ड, वर्कशॉप और फ़ूड-प्रोसेसिंग क्षेत्रों के सेंटर-पुल डिस्पेंसर के लिए उपयुक्त।', 'रसोई · अस्पताल · वर्कशॉप', NULL, NULL, NULL),
  ('DZIND-DF025', 'en', 'Kitchen Towel', 'Absorbent 2-ply kitchen towel - 60 pulls.', '2-ply, 60 pulls, Kitchen, Spills & oil', 'A two-ply kitchen towel roll with 60 sheets for wiping spills, draining fried snacks and quick clean-ups. Handy for home kitchens, bakeries and food stalls.', 'Home kitchens · Bakeries · Food stalls', NULL, 'dFresh Kitchen Towel - 2-ply · 60 pulls · 1 roll', 'Hi dFresh, I''m interested in DZIND-DF025 Kitchen Towel - please share price and minimum order.'),
  ('DZIND-DF025', 'ta', 'கிச்சன் டவல்', 'உறிஞ்சும் தன்மை கொண்ட 2-ப்ளை கிச்சன் டவல் - 60 ஷீட்கள்.', '2-ப்ளை, 60 ஷீட்கள், சமையலறை, கசிவு & எண்ணெய்', 'சிந்தியவற்றைத் துடைக்க, பொரித்த தின்பண்டங்களின் எண்ணெயை வடிக்க மற்றும் விரைவான சுத்தம் செய்ய 60 ஷீட்கள் கொண்ட இரட்டை அடுக்கு கிச்சன் டவல் ரோல். வீட்டுச் சமையலறைகள், பேக்கரிகள் மற்றும் உணவுக் கடைகளுக்கு வசதியானது.', 'வீட்டுச் சமையலறைகள் · பேக்கரிகள் · உணவுக் கடைகள்', NULL, NULL, NULL),
  ('DZIND-DF025', 'hi', 'किचन टॉवल', 'सोखने वाला 2-प्लाई किचन टॉवल - 60 शीट।', '2-प्लाई, 60 शीट, किचन, पानी व तेल', 'गिरी चीज़ें पोंछने, तले हुए नाश्ते का तेल सोखने और जल्दी सफ़ाई के लिए 60 शीट वाला दो-प्लाई किचन टॉवल रोल। घर की रसोई, बेकरी और फ़ूड स्टॉल के लिए उपयोगी।', 'घर की रसोई · बेकरी · फ़ूड स्टॉल', NULL, NULL, NULL),
  ('DZIND-DF026', 'en', 'Kitchen Towels - 2 Pack', 'Twin pack of 2-ply kitchen towels.', '2-ply, 2 × 60 pulls, Twin pack, Kitchen', 'Two rolls of our two-ply kitchen towel (60 sheets each) in one pack - so there''s always a spare roll in the kitchen. Ideal for busy homes, cafés and canteens.', 'Home · Cafés · Canteens', NULL, 'dFresh Kitchen Towels - 2 Pack - 2-ply · 2 × 60 pulls', 'Hi dFresh, I''m interested in DZIND-DF026 Kitchen Towels - 2 Pack - please share price and minimum order.'),
  ('DZIND-DF026', 'ta', 'கிச்சன் டவல்கள் - 2 பேக்', 'இரட்டை பேக் 2-ப்ளை கிச்சன் டவல்கள்.', '2-ப்ளை, 2 × 60 ஷீட்கள், இரட்டை பேக், சமையலறை', 'எங்கள் இரட்டை அடுக்கு கிச்சன் டவலின் இரண்டு ரோல்கள் (ஒவ்வொன்றிலும் 60 ஷீட்கள்) ஒரே பேக்கில் - சமையலறையில் எப்போதும் ஒரு கூடுதல் ரோல் இருக்கும். பரபரப்பான வீடுகள், கஃபேக்கள் மற்றும் கேன்டீன்களுக்கு ஏற்றது.', 'வீடு · கஃபேக்கள் · கேன்டீன்கள்', NULL, NULL, NULL),
  ('DZIND-DF026', 'hi', 'किचन टॉवल - 2 पैक', '2-प्लाई किचन टॉवल का ट्विन पैक।', '2-प्लाई, 2 × 60 शीट, ट्विन पैक, किचन', 'हमारे दो-प्लाई किचन टॉवल के दो रोल (हर रोल में 60 शीट) एक पैक में - ताकि रसोई में हमेशा एक अतिरिक्त रोल रहे। व्यस्त घरों, कैफ़े और कैंटीन के लिए आदर्श।', 'घर · कैफ़े · कैंटीन', NULL, NULL, NULL),
  ('DZIND-DF028', 'en', 'Facial Tissue - 100 Pulls', 'Soft 2-ply face tissues in a 100-pull box.', '2-ply, 100 pulls, ~20×20 cm, Box', 'Gentle two-ply facial tissues (about 20×20 cm) in a 100-pull box that sits neatly on a desk, dressing table, reception counter or in the car. Gentle, like you.', 'Home · Offices · Clinics', NULL, 'dFresh Facial Tissue - 100 Pulls - 2-ply · ~20×20 cm · 100 pulls', 'Hi dFresh, I''m interested in DZIND-DF028 Facial Tissue - 100 Pulls - please share price and minimum order.'),
  ('DZIND-DF028', 'ta', 'ஃபேஷியல் டிஷ்யூ - 100 ஷீட்கள்', '100 ஷீட் பெட்டியில் மென்மையான 2-ப்ளை ஃபேஷியல் டிஷ்யூ.', '2-ப்ளை, 100 ஷீட்கள், ~20×20 செ.மீ, பெட்டி', 'மேசை, டிரஸ்ஸிங் டேபிள், வரவேற்பு கவுண்டர் அல்லது காரில் நேர்த்தியாக இருக்கும் 100 ஷீட் பெட்டியில் மென்மையான இரட்டை அடுக்கு ஃபேஷியல் டிஷ்யூக்கள் (சுமார் 20×20 செ.மீ).', 'வீடு · அலுவலகங்கள் · கிளினிக்குகள்', NULL, NULL, NULL),
  ('DZIND-DF028', 'hi', 'फेशियल टिशू - 100 शीट', '100 शीट के बॉक्स में मुलायम 2-प्लाई फेशियल टिशू।', '2-प्लाई, 100 शीट, ~20×20 सेमी, बॉक्स', 'डेस्क, ड्रेसिंग टेबल, रिसेप्शन काउंटर या कार में आसानी से रखे जाने वाले 100 शीट के बॉक्स में कोमल दो-प्लाई फेशियल टिशू (लगभग 20×20 सेमी)।', 'घर · दफ़्तर · क्लिनिक', NULL, NULL, NULL),
  ('DZIND-DF030', 'en', 'Facial Tissue - 200 Pulls', 'Big 200-pull box for families and front desks.', '2-ply, 200 pulls, Big box, Family', 'Twice the tissues of our standard box - 200 soft two-ply pulls - for family living rooms, hotel rooms, reception desks and doctors'' consulting rooms.', 'Families · Hotel rooms · Reception desks', NULL, 'dFresh Facial Tissue - 200 Pulls - 2-ply · 200 pulls', 'Hi dFresh, I''m interested in DZIND-DF030 Facial Tissue - 200 Pulls - please share price and minimum order.'),
  ('DZIND-DF030', 'ta', 'ஃபேஷியல் டிஷ்யூ - 200 ஷீட்கள்', 'குடும்பங்கள் மற்றும் வரவேற்பு மேசைகளுக்கான பெரிய 200 ஷீட் பெட்டி.', '2-ப்ளை, 200 ஷீட்கள், பெரிய பெட்டி, குடும்பம்', 'எங்கள் வழக்கமான பெட்டியை விட இரு மடங்கு - 200 மென்மையான இரட்டை அடுக்கு ஷீட்கள் - குடும்ப வரவேற்பறைகள், ஹோட்டல் அறைகள், வரவேற்பு மேசைகள் மற்றும் மருத்துவர் ஆலோசனை அறைகளுக்கு.', 'குடும்பங்கள் · ஹோட்டல் அறைகள் · வரவேற்பு மேசைகள்', NULL, NULL, NULL),
  ('DZIND-DF030', 'hi', 'फेशियल टिशू - 200 शीट', 'परिवारों और फ़्रंट डेस्क के लिए 200 शीट का बड़ा बॉक्स।', '2-प्लाई, 200 शीट, बड़ा बॉक्स, परिवार', 'हमारे सामान्य बॉक्स से दोगुने टिशू - 200 मुलायम दो-प्लाई शीट - परिवार के लिविंग रूम, होटल के कमरों, रिसेप्शन डेस्क और डॉक्टरों के कंसल्टिंग रूम के लिए।', 'परिवार · होटल के कमरे · रिसेप्शन डेस्क', NULL, NULL, NULL),
  ('DZIND-DF031', 'en', 'Facial Tissue Soft Pack - 200', 'Value soft pack - 200 face tissues, no box.', '2-ply, 200 pulls, Soft pack, Value', 'The same soft two-ply face tissue in a flexible pack instead of a carton - lighter on the pocket and easy to keep in a bag, drawer or vehicle. 200 pulls.', 'Home · Shops · Travel', NULL, 'dFresh Facial Tissue Soft Pack - 200 - 2-ply · 200 pulls · soft pack', 'Hi dFresh, I''m interested in DZIND-DF031 Facial Tissue Soft Pack - 200 - please share price and minimum order.'),
  ('DZIND-DF031', 'ta', 'ஃபேஷியல் டிஷ்யூ சாஃப்ட் பேக் - 200', 'சிக்கனமான சாஃப்ட் பேக் - பெட்டி இல்லாமல் 200 ஃபேஷியல் டிஷ்யூக்கள்.', '2-ப்ளை, 200 ஷீட்கள், சாஃப்ட் பேக், சிக்கனம்', 'அட்டைப்பெட்டிக்குப் பதிலாக நெகிழ்வான பேக்கில் அதே மென்மையான இரட்டை அடுக்கு ஃபேஷியல் டிஷ்யூ - விலை குறைவு, பை, டிராயர் அல்லது வாகனத்தில் வைக்க எளிது. 200 ஷீட்கள்.', 'வீடு · கடைகள் · பயணம்', NULL, NULL, NULL),
  ('DZIND-DF031', 'hi', 'फेशियल टिशू सॉफ्ट पैक - 200', 'किफ़ायती सॉफ्ट पैक - बिना बॉक्स 200 फेशियल टिशू।', '2-प्लाई, 200 शीट, सॉफ्ट पैक, किफ़ायती', 'कार्टन की जगह लचीले पैक में वही मुलायम दो-प्लाई फेशियल टिशू - जेब पर हल्का और बैग, दराज़ या गाड़ी में रखना आसान। 200 शीट।', 'घर · दुकानें · यात्रा', NULL, NULL, NULL),
  ('DZIND-DF035', 'en', 'Pocket Tissues - 10 Pack', 'Ten pocket packs of 3-ply tissues for on-the-go.', '3-ply, 10 × 10 sheets, Pocket size, Travel', 'Ten handy pocket packs, each with ten three-ply tissues. Slip one into a pocket, handbag, school bag or glovebox - soft, strong tissues wherever you go.', 'Travel · Students · Medical shops', NULL, 'dFresh Pocket Tissues - 10 Pack - 3-ply · 10 packs × 10 sheets', 'Hi dFresh, I''m interested in DZIND-DF035 Pocket Tissues - 10 Pack - please share price and minimum order.'),
  ('DZIND-DF035', 'ta', 'பாக்கெட் டிஷ்யூ - 10 பேக்', 'பயணத்தின்போது பயன்படுத்த 3-ப்ளை டிஷ்யூ கொண்ட பத்து பாக்கெட் பேக்குகள்.', '3-ப்ளை, 10 × 10 ஷீட்கள், பாக்கெட் அளவு, பயணம்', 'பத்து வசதியான பாக்கெட் பேக்குகள், ஒவ்வொன்றிலும் பத்து மூன்று அடுக்கு டிஷ்யூக்கள். பாக்கெட், கைப்பை, பள்ளிப் பை அல்லது காரில் வைத்துக்கொள்ளுங்கள் - எங்கு சென்றாலும் மென்மையான டிஷ்யூ.', 'பயணம் · மாணவர்கள் · மருந்தகங்கள்', NULL, NULL, NULL),
  ('DZIND-DF035', 'hi', 'पॉकेट टिशू - 10 पैक', 'चलते-फिरते इस्तेमाल के लिए 3-प्लाई टिशू के दस पॉकेट पैक।', '3-प्लाई, 10 × 10 शीट, पॉकेट साइज़, यात्रा', 'दस सुविधाजनक पॉकेट पैक, हर एक में तीन-प्लाई के दस टिशू। जेब, हैंडबैग, स्कूल बैग या गाड़ी में रखें - जहाँ भी जाएँ, मुलायम टिशू साथ।', 'यात्रा · छात्र · मेडिकल स्टोर', NULL, NULL, NULL),
  ('DZIND-DF048', 'en', 'Bamboo Facial Tissue', 'Soft face tissues made from bamboo pulp.', 'Bamboo pulp, Facial tissue, Box, Premium', 'Facial tissues made from bamboo pulp - a premium choice for dressing tables, office desks and hotel rooms. Soft and smooth, in a dFresh box.', 'Home · Offices · Hotel rooms', NULL, 'dFresh Bamboo Facial Tissue - Bamboo pulp · ply and pull count to be confirmed', 'Hi dFresh, I''m interested in DZIND-DF048 Bamboo Facial Tissue - please share price and minimum order.'),
  ('DZIND-DF048', 'ta', 'மூங்கில் ஃபேஷியல் டிஷ்யூ', 'மூங்கில் கூழிலிருந்து தயாரிக்கப்பட்ட மென்மையான ஃபேஷியல் டிஷ்யூக்கள்.', 'மூங்கில் கூழ், ஃபேஷியல் டிஷ்யூ, பெட்டி, பிரீமியம்', 'மூங்கில் கூழிலிருந்து தயாரிக்கப்பட்ட ஃபேஷியல் டிஷ்யூக்கள் - டிரஸ்ஸிங் டேபிள்கள், அலுவலக மேசைகள் மற்றும் ஹோட்டல் அறைகளுக்கான பிரீமியம் தேர்வு. மென்மையானது, மிருதுவானது, dFresh பெட்டியில்.', 'வீடு · அலுவலகங்கள் · ஹோட்டல் அறைகள்', NULL, NULL, NULL),
  ('DZIND-DF048', 'hi', 'बांस फेशियल टिशू', 'बांस के पल्प से बने मुलायम फेशियल टिशू।', 'बांस पल्प, फेशियल टिशू, बॉक्स, प्रीमियम', 'बांस के पल्प से बने फेशियल टिशू - ड्रेसिंग टेबल, ऑफ़िस डेस्क और होटल के कमरों के लिए प्रीमियम पसंद। मुलायम और चिकने, dFresh बॉक्स में।', 'घर · दफ़्तर · होटल के कमरे', NULL, NULL, NULL),
  ('DZIND-DF036', 'en', 'C-fold Hand Towels', 'C-fold paper hand towels for washroom dispensers.', 'C-fold, 2-ply, 250 sheets, Washroom', 'Two-ply C-fold towels (250 sheets per pack) for drying hands in office, school, hospital and restaurant washrooms. Fits standard C-fold dispensers.', 'Offices · Schools · Hospitals', NULL, 'dFresh C-fold Hand Towels - 2-ply · C-fold · 250 sheets', 'Hi dFresh, I''m interested in DZIND-DF036 C-fold Hand Towels - please share price and minimum order.'),
  ('DZIND-DF036', 'ta', 'C-மடிப்பு ஹேண்ட் டவல்கள்', 'வாஷ்ரூம் டிஸ்பென்சர்களுக்கான C-மடிப்பு பேப்பர் ஹேண்ட் டவல்கள்.', 'C-மடிப்பு, 2-ப்ளை, 250 ஷீட்கள், வாஷ்ரூம்', 'அலுவலகம், பள்ளி, மருத்துவமனை மற்றும் உணவக வாஷ்ரூம்களில் கைகளைத் துடைக்க இரட்டை அடுக்கு C-மடிப்பு டவல்கள் (ஒரு பேக்கில் 250 ஷீட்கள்). வழக்கமான C-மடிப்பு டிஸ்பென்சர்களில் பொருந்தும்.', 'அலுவலகங்கள் · பள்ளிகள் · மருத்துவமனைகள்', NULL, NULL, NULL),
  ('DZIND-DF036', 'hi', 'C-फोल्ड हैंड टॉवल', 'वॉशरूम डिस्पेंसर के लिए C-फोल्ड पेपर हैंड टॉवल।', 'C-फोल्ड, 2-प्लाई, 250 शीट, वॉशरूम', 'दफ़्तर, स्कूल, अस्पताल और रेस्टोरेंट के वॉशरूम में हाथ सुखाने के लिए दो-प्लाई C-फोल्ड टॉवल (प्रति पैक 250 शीट)। सामान्य C-फोल्ड डिस्पेंसर में फिट।', 'दफ़्तर · स्कूल · अस्पताल', NULL, NULL, NULL),
  ('DZIND-DF037', 'en', 'M-fold Hand Towels', 'Strong M-fold hand towels - one sheet at a time.', 'M-fold, 31-35 GSM, 150 sheets, Washroom', 'Multifold (M-fold) paper towels of 31-35 GSM, 150 sheets per pack. Each pull dispenses a single towel, helping washrooms in offices, malls, hotels and factories stay tidy and stocked.', 'Offices · Malls · Hotels · Factories', NULL, 'dFresh M-fold Hand Towels - 1-ply · 31-35 GSM · M-fold · 150 sheets', 'Hi dFresh, I''m interested in DZIND-DF037 M-fold Hand Towels - please share price and minimum order.'),
  ('DZIND-DF037', 'ta', 'M-மடிப்பு ஹேண்ட் டவல்கள்', 'வலுவான M-மடிப்பு ஹேண்ட் டவல்கள் - ஒரு முறைக்கு ஒரு ஷீட்.', 'M-மடிப்பு, 31-35 GSM, 150 ஷீட்கள், வாஷ்ரூம்', '31-35 GSM மல்டிஃபோல்டு (M-மடிப்பு) பேப்பர் டவல்கள், ஒரு பேக்கில் 150 ஷீட்கள். ஒவ்வொரு முறையும் ஒரு டவல் மட்டுமே வெளிவருவதால், அலுவலகங்கள், மால்கள், ஹோட்டல்கள் மற்றும் தொழிற்சாலைகளின் வாஷ்ரூம்கள் நேர்த்தியாக இருக்க உதவுகிறது.', 'அலுவலகங்கள் · மால்கள் · ஹோட்டல்கள் · தொழிற்சாலைகள்', NULL, NULL, NULL),
  ('DZIND-DF037', 'hi', 'M-फोल्ड हैंड टॉवल', 'मज़बूत M-फोल्ड हैंड टॉवल - एक बार में एक शीट।', 'M-फोल्ड, 31-35 GSM, 150 शीट, वॉशरूम', '31-35 GSM के मल्टीफोल्ड (M-फोल्ड) पेपर टॉवल, प्रति पैक 150 शीट। हर बार एक ही टॉवल निकलता है, जिससे दफ़्तरों, मॉल, होटलों और फ़ैक्टरियों के वॉशरूम साफ़-सुथरे रहते हैं।', 'दफ़्तर · मॉल · होटल · फ़ैक्टरियाँ', NULL, NULL, NULL),
  ('DZIND-DF038', 'en', 'V-fold Hand Towels', 'Premium 2-ply V-fold towels for executive washrooms.', 'V-fold, 2-ply, 34 GSM, 150 sheets', 'Two-ply V-fold hand towels (34 GSM, 150 sheets) with a softer, thicker feel - suited to corporate offices, hotel lobbies and premium restaurants.', 'Corporate offices · Hotel lobbies · Premium restaurants', NULL, 'dFresh V-fold Hand Towels - 2-ply · 34 GSM · V-fold · 150 sheets', 'Hi dFresh, I''m interested in DZIND-DF038 V-fold Hand Towels - please share price and minimum order.'),
  ('DZIND-DF038', 'ta', 'V-மடிப்பு ஹேண்ட் டவல்கள்', 'உயர்தர வாஷ்ரூம்களுக்கான பிரீமியம் 2-ப்ளை V-மடிப்பு டவல்கள்.', 'V-மடிப்பு, 2-ப்ளை, 34 GSM, 150 ஷீட்கள்', 'மென்மையான, தடிமனான உணர்வு கொண்ட இரட்டை அடுக்கு V-மடிப்பு ஹேண்ட் டவல்கள் (34 GSM, 150 ஷீட்கள்) - கார்ப்பரேட் அலுவலகங்கள், ஹோட்டல் லாபிகள் மற்றும் பிரீமியம் உணவகங்களுக்கு ஏற்றது.', 'கார்ப்பரேட் அலுவலகங்கள் · ஹோட்டல் லாபிகள் · பிரீமியம் உணவகங்கள்', NULL, NULL, NULL),
  ('DZIND-DF038', 'hi', 'V-फोल्ड हैंड टॉवल', 'एग्ज़ीक्यूटिव वॉशरूम के लिए प्रीमियम 2-प्लाई V-फोल्ड टॉवल।', 'V-फोल्ड, 2-प्लाई, 34 GSM, 150 शीट', 'मुलायम और मोटे एहसास वाले दो-प्लाई V-फोल्ड हैंड टॉवल (34 GSM, 150 शीट) - कॉर्पोरेट दफ़्तरों, होटल लॉबी और प्रीमियम रेस्टोरेंट के लिए उपयुक्त।', 'कॉर्पोरेट दफ़्तर · होटल लॉबी · प्रीमियम रेस्टोरेंट', NULL, NULL, NULL),
  ('DZIND-DF040', 'en', 'Interfold Towels', 'Interfolded towels that dispense neatly, sheet by sheet.', 'Interfold / N-fold, 100 sheets, Dispenser, Food service', 'Interfolded (N-fold) paper towels, 100 sheets per pack, for compact dispensers in quick-service restaurants, office pantries and clinics. The next sheet is always ready to pull.', 'Quick-service restaurants · Office pantries · Clinics', NULL, 'dFresh Interfold Towels - 1-2 ply · interfold (N-fold) · 100 sheets', 'Hi dFresh, I''m interested in DZIND-DF040 Interfold Towels - please share price and minimum order.'),
  ('DZIND-DF040', 'ta', 'இன்டர்ஃபோல்டு டவல்கள்', 'ஒவ்வொரு ஷீட்டாக நேர்த்தியாக வெளிவரும் இன்டர்ஃபோல்டு டவல்கள்.', 'இன்டர்ஃபோல்டு / N-மடிப்பு, 100 ஷீட்கள், டிஸ்பென்சர், உணவு சேவை', 'குயிக்-சர்வீஸ் உணவகங்கள், அலுவலக பேன்ட்ரிகள் மற்றும் கிளினிக்குகளில் உள்ள சிறிய டிஸ்பென்சர்களுக்கான இன்டர்ஃபோல்டு (N-மடிப்பு) பேப்பர் டவல்கள், ஒரு பேக்கில் 100 ஷீட்கள். அடுத்த ஷீட் எப்போதும் இழுக்கத் தயாராக இருக்கும்.', 'குயிக்-சர்வீஸ் உணவகங்கள் · அலுவலக பேன்ட்ரிகள் · கிளினிக்குகள்', NULL, NULL, NULL),
  ('DZIND-DF040', 'hi', 'इंटरफोल्ड टॉवल', 'एक-एक शीट करके सलीके से निकलने वाले इंटरफोल्ड टॉवल।', 'इंटरफोल्ड / N-फोल्ड, 100 शीट, डिस्पेंसर, फ़ूड सर्विस', 'क्विक-सर्विस रेस्टोरेंट, ऑफ़िस पैंट्री और क्लिनिक के कॉम्पैक्ट डिस्पेंसर के लिए इंटरफोल्ड (N-फोल्ड) पेपर टॉवल, प्रति पैक 100 शीट। अगली शीट हमेशा खींचने के लिए तैयार।', 'क्विक-सर्विस रेस्टोरेंट · ऑफ़िस पैंट्री · क्लिनिक', NULL, NULL, NULL),
  ('DZIND-DF044', 'en', 'Refreshing Wet Wipes - Sachets', 'Lemon-fresh wet wipes in single sachets for diners.', 'Single sachet, Lemon, ~15×20 cm, 100 per box', 'Individually sealed refreshing wipes (about 15×20 cm) with a light lemon fragrance. Serve one with every meal, room or travel kit - a small touch guests notice. Box of 100 sachets.', 'Restaurants · Hotels · Caterers · Travel', NULL, 'dFresh Refreshing Wet Wipes - Sachets - Single sachet · ~15×20 cm wipe · lemon fragrance', 'Hi dFresh, I''m interested in DZIND-DF044 Refreshing Wet Wipes - Sachets - please share price and minimum order.'),
  ('DZIND-DF044', 'ta', 'புத்துணர்ச்சி வெட் வைப்ஸ் - சாஷேக்கள்', 'உணவருந்துவோருக்கு தனித்தனி சாஷேக்களில் எலுமிச்சை மணம் கொண்ட வெட் வைப்ஸ்.', 'தனி சாஷே, எலுமிச்சை, ~15×20 செ.மீ, ஒரு பெட்டியில் 100', 'லேசான எலுமிச்சை மணம் கொண்ட, தனித்தனியாக சீல் செய்யப்பட்ட புத்துணர்ச்சி வைப்ஸ் (சுமார் 15×20 செ.மீ). ஒவ்வொரு உணவு, அறை அல்லது பயணக் கிட்டுடனும் ஒன்றை வழங்குங்கள் - விருந்தினர்கள் கவனிக்கும் சிறிய அக்கறை. 100 சாஷேக்கள் கொண்ட பெட்டி.', 'உணவகங்கள் · ஹோட்டல்கள் · கேட்டரர்கள் · பயணம்', NULL, NULL, NULL),
  ('DZIND-DF044', 'hi', 'रिफ़्रेशिंग वेट वाइप्स - सैशे', 'भोजन करने वालों के लिए अलग-अलग सैशे में नींबू की ताज़गी वाले वेट वाइप्स।', 'सिंगल सैशे, नींबू, ~15×20 सेमी, एक बॉक्स में 100', 'हल्की नींबू की खुशबू वाले, अलग-अलग सील किए गए रिफ़्रेशिंग वाइप्स (लगभग 15×20 सेमी)। हर भोजन, कमरे या ट्रैवल किट के साथ एक दें - एक छोटा सा ध्यान जो मेहमान नोटिस करते हैं। 100 सैशे का बॉक्स।', 'रेस्टोरेंट · होटल · कैटरर्स · यात्रा', NULL, NULL, NULL);

INSERT INTO product_images (product_id, position, file_name, width, height) VALUES
  ('DZIND-DF001', 1, 'DZIND-DF001_1.webp', 1200, 1200),
  ('DZIND-DF001', 2, 'DZIND-DF001_2.webp', 1200, 1200),
  ('DZIND-DF001', 3, 'DZIND-DF001_3.webp', 1200, 1200),
  ('DZIND-DF002', 1, 'DZIND-DF002_1.webp', 1200, 1200),
  ('DZIND-DF002', 2, 'DZIND-DF002_2.webp', 1200, 1200),
  ('DZIND-DF002', 3, 'DZIND-DF002_3.webp', 1200, 1200),
  ('DZIND-DF006', 1, 'DZIND-DF006_1.webp', 1200, 1200),
  ('DZIND-DF006', 2, 'DZIND-DF006_2.webp', 1200, 1200),
  ('DZIND-DF006', 3, 'DZIND-DF006_3.webp', 1200, 1200),
  ('DZIND-DF007', 1, 'DZIND-DF007_1.webp', 1200, 1200),
  ('DZIND-DF007', 2, 'DZIND-DF007_2.webp', 1200, 1200),
  ('DZIND-DF007', 3, 'DZIND-DF007_3.webp', 1200, 1200),
  ('DZIND-DF008', 1, 'DZIND-DF008_1.webp', 1200, 1200),
  ('DZIND-DF008', 2, 'DZIND-DF008_2.webp', 1200, 1200),
  ('DZIND-DF008', 3, 'DZIND-DF008_3.webp', 1200, 1200),
  ('DZIND-DF008-BLK', 1, 'DZIND-DF008-BLK_1.webp', 1200, 1200),
  ('DZIND-DF008-BLK', 2, 'DZIND-DF008-BLK_2.webp', 1200, 1200),
  ('DZIND-DF008-BLK', 3, 'DZIND-DF008-BLK_3.webp', 1200, 1200),
  ('DZIND-DF008-BUR', 1, 'DZIND-DF008-BUR_1.webp', 1200, 1200),
  ('DZIND-DF008-BUR', 2, 'DZIND-DF008-BUR_2.webp', 1200, 1200),
  ('DZIND-DF008-BUR', 3, 'DZIND-DF008-BUR_3.webp', 1200, 1200),
  ('DZIND-DF008-LAV', 1, 'DZIND-DF008-LAV_1.webp', 1200, 1200),
  ('DZIND-DF008-LAV', 2, 'DZIND-DF008-LAV_2.webp', 1200, 1200),
  ('DZIND-DF008-LAV', 3, 'DZIND-DF008-LAV_3.webp', 1200, 1200),
  ('DZIND-DF013', 1, 'DZIND-DF013_1.webp', 1200, 1200),
  ('DZIND-DF013', 2, 'DZIND-DF013_2.webp', 1200, 1200),
  ('DZIND-DF013', 3, 'DZIND-DF013_3.webp', 1200, 1200),
  ('DZIND-DF014', 1, 'DZIND-DF014_1.webp', 1200, 1200),
  ('DZIND-DF014', 2, 'DZIND-DF014_2.webp', 1200, 1200),
  ('DZIND-DF014', 3, 'DZIND-DF014_3.webp', 1200, 1200),
  ('DZIND-DF016', 1, 'DZIND-DF016_1.webp', 1200, 1200),
  ('DZIND-DF016', 2, 'DZIND-DF016_2.webp', 1200, 1200),
  ('DZIND-DF016', 3, 'DZIND-DF016_3.webp', 1200, 1200),
  ('DZIND-DF017', 1, 'DZIND-DF017_1.webp', 1200, 1200),
  ('DZIND-DF017', 2, 'DZIND-DF017_2.webp', 1200, 1200),
  ('DZIND-DF017', 3, 'DZIND-DF017_3.webp', 1200, 1200),
  ('DZIND-DF018', 1, 'DZIND-DF018_1.webp', 1200, 1200),
  ('DZIND-DF018', 2, 'DZIND-DF018_2.webp', 1200, 1200),
  ('DZIND-DF018', 3, 'DZIND-DF018_3.webp', 1200, 1200),
  ('DZIND-DF019', 1, 'DZIND-DF019_1.webp', 1200, 1200),
  ('DZIND-DF019', 2, 'DZIND-DF019_2.webp', 1200, 1200),
  ('DZIND-DF019', 3, 'DZIND-DF019_3.webp', 1200, 1200),
  ('DZIND-DF023', 1, 'DZIND-DF023_1.webp', 1200, 1200),
  ('DZIND-DF023', 2, 'DZIND-DF023_2.webp', 1200, 1200),
  ('DZIND-DF023', 3, 'DZIND-DF023_3.webp', 1200, 1200),
  ('DZIND-DF024', 1, 'DZIND-DF024_1.webp', 1200, 1200),
  ('DZIND-DF024', 2, 'DZIND-DF024_2.webp', 1200, 1200),
  ('DZIND-DF024', 3, 'DZIND-DF024_3.webp', 1200, 1200),
  ('DZIND-DF025', 1, 'DZIND-DF025_1.webp', 1200, 1200),
  ('DZIND-DF025', 2, 'DZIND-DF025_2.webp', 1200, 1200),
  ('DZIND-DF025', 3, 'DZIND-DF025_3.webp', 1200, 1200),
  ('DZIND-DF026', 1, 'DZIND-DF026_1.webp', 1200, 1200),
  ('DZIND-DF026', 2, 'DZIND-DF026_2.webp', 1200, 1200),
  ('DZIND-DF026', 3, 'DZIND-DF026_3.webp', 1200, 1200),
  ('DZIND-DF028', 1, 'DZIND-DF028_1.webp', 1200, 1200),
  ('DZIND-DF028', 2, 'DZIND-DF028_2.webp', 1200, 1200),
  ('DZIND-DF028', 3, 'DZIND-DF028_3.webp', 1200, 1200),
  ('DZIND-DF030', 1, 'DZIND-DF030_1.webp', 1200, 1200),
  ('DZIND-DF030', 2, 'DZIND-DF030_2.webp', 1200, 1200),
  ('DZIND-DF030', 3, 'DZIND-DF030_3.webp', 1200, 1200),
  ('DZIND-DF031', 1, 'DZIND-DF031_1.webp', 1200, 1200),
  ('DZIND-DF031', 2, 'DZIND-DF031_2.webp', 1200, 1200),
  ('DZIND-DF031', 3, 'DZIND-DF031_3.webp', 1200, 1200),
  ('DZIND-DF035', 1, 'DZIND-DF035_1.webp', 1200, 1200),
  ('DZIND-DF035', 2, 'DZIND-DF035_2.webp', 1200, 1200),
  ('DZIND-DF035', 3, 'DZIND-DF035_3.webp', 1200, 1200),
  ('DZIND-DF048', 1, 'DZIND-DF048_1.webp', 1200, 1200),
  ('DZIND-DF048', 2, 'DZIND-DF048_2.webp', 1200, 1200),
  ('DZIND-DF048', 3, 'DZIND-DF048_3.webp', 1200, 1200),
  ('DZIND-DF036', 1, 'DZIND-DF036_1.webp', 1200, 1200),
  ('DZIND-DF036', 2, 'DZIND-DF036_2.webp', 1200, 1200),
  ('DZIND-DF036', 3, 'DZIND-DF036_3.webp', 1200, 1200),
  ('DZIND-DF037', 1, 'DZIND-DF037_1.webp', 1200, 1200),
  ('DZIND-DF037', 2, 'DZIND-DF037_2.webp', 1200, 1200),
  ('DZIND-DF037', 3, 'DZIND-DF037_3.webp', 1200, 1200),
  ('DZIND-DF038', 1, 'DZIND-DF038_1.webp', 1200, 1200),
  ('DZIND-DF038', 2, 'DZIND-DF038_2.webp', 1200, 1200),
  ('DZIND-DF038', 3, 'DZIND-DF038_3.webp', 1200, 1200),
  ('DZIND-DF040', 1, 'DZIND-DF040_1.webp', 1200, 1200),
  ('DZIND-DF040', 2, 'DZIND-DF040_2.webp', 1200, 1200),
  ('DZIND-DF040', 3, 'DZIND-DF040_3.webp', 1200, 1200),
  ('DZIND-DF044', 1, 'DZIND-DF044_1.webp', 1200, 1200),
  ('DZIND-DF044', 2, 'DZIND-DF044_2.webp', 1200, 1200),
  ('DZIND-DF044', 3, 'DZIND-DF044_3.webp', 1200, 1200);

INSERT INTO size_picker (position, product_id, size_label, scale, is_default) VALUES
  (1, 'DZIND-DF001', '20×20', 0.62, 0),
  (2, 'DZIND-DF002', '22×22', 0.68, 0),
  (3, 'DZIND-DF006', '27×27', 0.8, 0),
  (4, 'DZIND-DF007', '30×30', 0.88, 1),
  (5, 'DZIND-DF013', '40×40', 1, 0);

INSERT INTO banners (banner_key, sort_order, theme, cta_action, cta_target, desktop_file, mobile_file, is_active, note) VALUES
  ('home', 1, 'light', 'products', NULL, 'dFresh_Banner_home_1920x800.webp', 'dFresh_Banner_home_1080x1350.webp', 1, NULL),
  ('forhome', 2, 'light', 'products_home', NULL, 'dFresh_Banner_forhome_1920x800.webp', 'dFresh_Banner_forhome_1080x1350.webp', 1, NULL),
  ('products', 3, 'light', 'products', NULL, 'dFresh_Banner_products_1920x800.webp', 'dFresh_Banner_products_1080x1350.webp', 1, NULL),
  ('business', 4, 'light', 'section', 'business', 'dFresh_Banner_business_1920x800.webp', 'dFresh_Banner_business_1080x1350.webp', 1, NULL),
  ('colours', 5, 'dark', 'products_category', 'napkins', 'dFresh_Banner_colours_1920x800.webp', 'dFresh_Banner_colours_1080x1350.webp', 1, NULL),
  ('classic', 6, 'dark', 'products', NULL, 'dFresh_Banner_classic_1920x800.webp', 'dFresh_Banner_classic_1080x1350.webp', 1, NULL),
  ('rich', 7, 'dark', 'products_category', 'napkins', 'dFresh_Banner_rich_1920x800.webp', 'dFresh_Banner_rich_1080x1350.webp', 1, NULL),
  ('about', 8, 'light', 'form', 'sample', 'dFresh_Banner_about_1920x800.webp', 'dFresh_Banner_about_1080x1350.webp', 1, NULL),
  ('funky', 9, 'light', 'products_home', NULL, 'dFresh_Banner_funky_1920x800.webp', 'dFresh_Banner_funky_1080x1350.webp', 0, 'Inactive until approved by the Director (brief: do not make the site funky)'),
  ('neon', 10, 'dark', 'products', NULL, 'dFresh_Banner_neon_1920x800.webp', 'dFresh_Banner_neon_1080x1350.webp', 0, 'Inactive until approved by the Director (brief: do not make the site funky)'),
  ('rainbow', 11, 'light', 'products', NULL, 'dFresh_Banner_rainbow_1920x800.webp', 'dFresh_Banner_rainbow_1080x1350.webp', 0, 'Inactive until approved by the Director (brief: do not make the site funky)');

INSERT INTO banner_translations (banner_key, lang_code, headline, cta_label) VALUES
  ('home', 'en', 'Soft for every corner of home.', 'See all products'),
  ('home', 'ta', 'வீட்டின் ஒவ்வொரு மூலைக்கும் மென்மை.', 'அனைத்து பொருட்களும்'),
  ('home', 'hi', 'घर के हर कोने के लिए कोमलता।', 'सभी उत्पाद'),
  ('forhome', 'en', 'Everyday softness for the family.', 'Home products'),
  ('forhome', 'ta', 'குடும்பத்துக்கு அன்றாட மென்மை.', 'வீட்டுப் பொருட்கள்'),
  ('forhome', 'hi', 'परिवार के लिए रोज़ की कोमलता।', 'घर के उत्पाद'),
  ('products', 'en', '25 products. One gentle brand.', 'See all products'),
  ('products', 'ta', '25 பொருட்கள். ஒரே மென்மையான பிராண்ட்.', 'அனைத்து பொருட்களும்'),
  ('products', 'hi', '25 उत्पाद। एक कोमल ब्रांड।', 'सभी उत्पाद'),
  ('business', 'en', 'Washroom-ready for business.', 'Business kits'),
  ('business', 'ta', 'வணிக வாஷ்ரூம்களுக்குத் தயார்.', 'வணிக கிட்கள்'),
  ('business', 'hi', 'व्यवसाय के वॉशरूम के लिए तैयार।', 'बिज़नेस किट'),
  ('colours', 'en', 'Napkins in Black, Burgundy and Lavender.', 'See napkins'),
  ('colours', 'ta', 'கருப்பு, பர்கண்டி, லாவெண்டர் நிறங்களில் நாப்கின்கள்.', 'நாப்கின்கள்'),
  ('colours', 'hi', 'काले, बरगंडी और लैवेंडर रंग में नैपकिन।', 'नैपकिन देखें'),
  ('classic', 'en', 'Classic white. Always right.', 'See all products'),
  ('classic', 'ta', 'கிளாசிக் வெள்ளை. எப்போதும் சரி.', 'அனைத்து பொருட்களும்'),
  ('classic', 'hi', 'क्लासिक सफ़ेद। हमेशा सही।', 'सभी उत्पाद'),
  ('rich', 'en', 'Premium and airlaid for grand occasions.', 'See napkins'),
  ('rich', 'ta', 'பெரிய விழாக்களுக்கு பிரீமியம் ஏர்லெய்டு.', 'நாப்கின்கள்'),
  ('rich', 'hi', 'बड़े मौकों के लिए प्रीमियम और एयरलेड।', 'नैपकिन देखें'),
  ('about', 'en', 'Packed and shipped from Kanchipuram.', 'Get a free sample'),
  ('about', 'ta', 'காஞ்சிபுரத்திலிருந்து பேக் செய்து அனுப்பப்படுகிறது.', 'இலவச மாதிரி'),
  ('about', 'hi', 'कांचीपुरम से पैक करके भेजा जाता है।', 'मुफ़्त सैंपल'),
  ('funky', 'en', 'Fun, bright and family-sized.', 'Home products'),
  ('funky', 'ta', 'மகிழ்ச்சியான, குடும்ப அளவு.', 'வீட்டுப் பொருட்கள்'),
  ('funky', 'hi', 'मज़ेदार, चमकीला, परिवार के लिए।', 'घर के उत्पाद'),
  ('neon', 'en', 'Party-ready after dark.', 'See all products'),
  ('neon', 'ta', 'இரவு விருந்துக்குத் தயார்.', 'அனைத்து பொருட்களும்'),
  ('neon', 'hi', 'रात की पार्टी के लिए तैयार।', 'सभी उत्पाद'),
  ('rainbow', 'en', 'Gentle in every colour.', 'See all products'),
  ('rainbow', 'ta', 'ஒவ்வொரு நிறத்திலும் மென்மை.', 'அனைத்து பொருட்களும்'),
  ('rainbow', 'hi', 'हर रंग में कोमल।', 'सभी उत्पाद');

INSERT INTO kits (kit_key, sort_order, business_type, rep_product_id, is_active) VALUES
  ('hotels', 1, 'hotel', 'DZIND-DF030', 1),
  ('restaurants', 2, 'restaurant', 'DZIND-DF007', 1),
  ('offices', 3, 'office', 'DZIND-DF037', 1),
  ('hospitals', 4, 'hospital', 'DZIND-DF019', 1);

INSERT INTO kit_translations (kit_key, lang_code, name, tagline) VALUES
  ('hotels', 'en', 'Hotels & lodges', 'Rooms, restaurant and lobby washrooms from one supplier.'),
  ('hotels', 'ta', 'ஹோட்டல்கள் & லாட்ஜ்கள்', 'அறைகள், உணவகம், லாபி வாஷ்ரூம்கள், அனைத்தும் ஒரே சப்ளையரிடமிருந்து.'),
  ('hotels', 'hi', 'होटल और लॉज', 'कमरे, रेस्टोरेंट और लॉबी वॉशरूम, सब एक सप्लायर से।'),
  ('restaurants', 'en', 'Restaurants & caterers', 'From the tea counter to the wedding banquet.'),
  ('restaurants', 'ta', 'உணவகங்கள் & கேட்டரர்கள்', 'டீ கவுண்டர் முதல் திருமண விருந்து வரை.'),
  ('restaurants', 'hi', 'रेस्टोरेंट और कैटरर्स', 'चाय काउंटर से शादी की दावत तक।'),
  ('offices', 'en', 'Offices & factories', 'Washrooms and pantries that stay stocked.'),
  ('offices', 'ta', 'அலுவலகங்கள் & தொழிற்சாலைகள்', 'எப்போதும் இருப்புள்ள வாஷ்ரூம்கள் மற்றும் பேன்ட்ரிகள்.'),
  ('offices', 'hi', 'ऑफ़िस और फ़ैक्टरी', 'हमेशा भरे रहने वाले वॉशरूम और पैंट्री।'),
  ('hospitals', 'en', 'Hospitals & clinics', 'Wards, consulting rooms and reception desks.'),
  ('hospitals', 'ta', 'மருத்துவமனைகள் & கிளினிக்குகள்', 'வார்டுகள், ஆலோசனை அறைகள், வரவேற்பு மேசைகள்.'),
  ('hospitals', 'hi', 'अस्पताल और क्लिनिक', 'वार्ड, कंसल्टिंग रूम और रिसेप्शन डेस्क।');

INSERT INTO kit_products (kit_key, product_id, sort_order) VALUES
  ('hotels', 'DZIND-DF006', 1),
  ('hotels', 'DZIND-DF019', 2),
  ('hotels', 'DZIND-DF030', 3),
  ('hotels', 'DZIND-DF044', 4),
  ('restaurants', 'DZIND-DF002', 1),
  ('restaurants', 'DZIND-DF007', 2),
  ('restaurants', 'DZIND-DF013', 3),
  ('restaurants', 'DZIND-DF014', 4),
  ('offices', 'DZIND-DF019', 1),
  ('offices', 'DZIND-DF023', 2),
  ('offices', 'DZIND-DF037', 3),
  ('offices', 'DZIND-DF040', 4),
  ('hospitals', 'DZIND-DF024', 1),
  ('hospitals', 'DZIND-DF036', 2),
  ('hospitals', 'DZIND-DF040', 3),
  ('hospitals', 'DZIND-DF028', 4);

INSERT INTO towns (town_key, sort_order, is_base, map_x, map_y, lat, lng, is_active) VALUES
  ('kanchipuram', 1, 1, 358, 247, 12.834, 79.703, 1),
  ('chennai', 2, 0, 522, 107, 13.083, 80.27, 1),
  ('sriperumbudur', 3, 0, 427, 169, 12.968, 79.947, 1),
  ('wallajabad', 4, 0, 392, 280, 12.791, 79.823, 1),
  ('vellore', 5, 0, 193, 197, 12.916, 79.133, 1),
  ('ambur', 6, 0, 75, 270, 12.791, 78.716, 1);

INSERT INTO town_translations (town_key, lang_code, name) VALUES
  ('kanchipuram', 'en', 'Kanchipuram'),
  ('kanchipuram', 'ta', 'காஞ்சிபுரம்'),
  ('kanchipuram', 'hi', 'कांचीपुरम'),
  ('chennai', 'en', 'Chennai'),
  ('chennai', 'ta', 'சென்னை'),
  ('chennai', 'hi', 'चेन्नई'),
  ('sriperumbudur', 'en', 'Sriperumbudur'),
  ('sriperumbudur', 'ta', 'ஸ்ரீபெரும்புதூர்'),
  ('sriperumbudur', 'hi', 'श्रीपेरुम्बुदूर'),
  ('wallajabad', 'en', 'Wallajabad'),
  ('wallajabad', 'ta', 'வாலாஜாபாத்'),
  ('wallajabad', 'hi', 'वालाजाबाद'),
  ('vellore', 'en', 'Vellore'),
  ('vellore', 'ta', 'வேலூர்'),
  ('vellore', 'hi', 'वेल्लोर'),
  ('ambur', 'en', 'Ambur'),
  ('ambur', 'ta', 'ஆம்பூர்'),
  ('ambur', 'hi', 'आम्बूर');

INSERT INTO form_options (list_key, option_value, sort_order, is_active) VALUES
  ('business_type', 'hotel', 1, 1),
  ('business_type', 'restaurant', 2, 1),
  ('business_type', 'office', 3, 1),
  ('business_type', 'factory', 4, 1),
  ('business_type', 'hospital', 5, 1),
  ('business_type', 'shop', 6, 1),
  ('business_type', 'other', 7, 1),
  ('monthly_sales', 'under_50k', 1, 1),
  ('monthly_sales', '50k_2l', 2, 1),
  ('monthly_sales', '2l_5l', 3, 1),
  ('monthly_sales', 'above_5l', 4, 1),
  ('yes_no', 'yes', 1, 1),
  ('yes_no', 'no', 2, 1);

INSERT INTO form_option_translations (list_key, option_value, lang_code, label) VALUES
  ('business_type', 'hotel', 'en', 'Hotel / lodge'),
  ('business_type', 'hotel', 'ta', 'ஹோட்டல் / லாட்ஜ்'),
  ('business_type', 'hotel', 'hi', 'होटल / लॉज'),
  ('business_type', 'restaurant', 'en', 'Restaurant / caterer'),
  ('business_type', 'restaurant', 'ta', 'உணவகம் / கேட்டரர்'),
  ('business_type', 'restaurant', 'hi', 'रेस्टोरेंट / कैटरर'),
  ('business_type', 'office', 'en', 'Office'),
  ('business_type', 'office', 'ta', 'அலுவலகம்'),
  ('business_type', 'office', 'hi', 'ऑफ़िस'),
  ('business_type', 'factory', 'en', 'Factory'),
  ('business_type', 'factory', 'ta', 'தொழிற்சாலை'),
  ('business_type', 'factory', 'hi', 'फ़ैक्टरी'),
  ('business_type', 'hospital', 'en', 'Hospital / clinic'),
  ('business_type', 'hospital', 'ta', 'மருத்துவமனை / கிளினிக்'),
  ('business_type', 'hospital', 'hi', 'अस्पताल / क्लिनिक'),
  ('business_type', 'shop', 'en', 'Shop'),
  ('business_type', 'shop', 'ta', 'கடை'),
  ('business_type', 'shop', 'hi', 'दुकान'),
  ('business_type', 'other', 'en', 'Other'),
  ('business_type', 'other', 'ta', 'மற்றவை'),
  ('business_type', 'other', 'hi', 'अन्य'),
  ('monthly_sales', 'under_50k', 'en', 'Under ₹50,000'),
  ('monthly_sales', 'under_50k', 'ta', '₹50,000க்குக் கீழ்'),
  ('monthly_sales', 'under_50k', 'hi', '₹50,000 से कम'),
  ('monthly_sales', '50k_2l', 'en', '₹50,000 - ₹2 lakh'),
  ('monthly_sales', '50k_2l', 'ta', '₹50,000 - ₹2 லட்சம்'),
  ('monthly_sales', '50k_2l', 'hi', '₹50,000 - ₹2 लाख'),
  ('monthly_sales', '2l_5l', 'en', '₹2 - 5 lakh'),
  ('monthly_sales', '2l_5l', 'ta', '₹2 - 5 லட்சம்'),
  ('monthly_sales', '2l_5l', 'hi', '₹2 - 5 लाख'),
  ('monthly_sales', 'above_5l', 'en', 'Above ₹5 lakh'),
  ('monthly_sales', 'above_5l', 'ta', '₹5 லட்சத்துக்கு மேல்'),
  ('monthly_sales', 'above_5l', 'hi', '₹5 लाख से ज़्यादा'),
  ('yes_no', 'yes', 'en', 'Yes'),
  ('yes_no', 'yes', 'ta', 'ஆம்'),
  ('yes_no', 'yes', 'hi', 'हाँ'),
  ('yes_no', 'no', 'en', 'No'),
  ('yes_no', 'no', 'ta', 'இல்லை'),
  ('yes_no', 'no', 'hi', 'नहीं');

INSERT INTO ui_text_keys (text_key, group_name, description, allows_html) VALUES
  ('ab1_h', 'about', 'From approved preview v3', 0),
  ('ab1_p', 'about', 'From approved preview v3', 0),
  ('ab2_h', 'about', 'From approved preview v3', 0),
  ('ab2_p', 'about', 'From approved preview v3', 0),
  ('ab3_h', 'about', 'From approved preview v3', 0),
  ('ab3_p', 'about', 'From approved preview v3', 0),
  ('ab_h', 'about', 'From approved preview v3', 0),
  ('ab_k', 'about', 'From approved preview v3', 0),
  ('ab_p', 'about', 'From approved preview v3', 0),
  ('all', 'common', 'From UI_Text sheet (Excel)', 0),
  ('all_h', 'common', 'From approved preview v3', 0),
  ('back', 'common', 'From UI_Text sheet (Excel)', 0),
  ('band_h', 'contact', 'From approved preview v3', 0),
  ('band_p', 'contact', 'From approved preview v3', 0),
  ('become_distributor', 'common', 'From UI_Text sheet (Excel)', 0),
  ('best_for', 'common', 'From UI_Text sheet (Excel)', 0),
  ('biz_h', 'business', 'From approved preview v3', 0),
  ('biz_p', 'business', 'From approved preview v3', 0),
  ('brand_line', 'common', 'From UI_Text sheet (Excel)', 0),
  ('bro_pending', 'common', 'From approved preview v3', 0),
  ('brochure', 'common', 'From approved preview v3', 0),
  ('c_godown', 'contact', 'From approved preview v3', 0),
  ('c_godown_a', 'contact', 'From approved preview v3', 0),
  ('c_map', 'contact', 'From approved preview v3', 0),
  ('c_office', 'contact', 'From approved preview v3', 0),
  ('c_office_a', 'contact', 'From approved preview v3', 0),
  ('choose', 'common', 'From approved preview v3', 0),
  ('close', 'common', 'From approved preview v3', 0),
  ('colour', 'common', 'From UI_Text sheet (Excel)', 0),
  ('consent', 'common', 'From UI_Text sheet (Excel)', 0),
  ('db_go', 'doors', 'From approved preview v3', 0),
  ('db_h', 'doors', 'From approved preview v3', 0),
  ('db_p', 'doors', 'From approved preview v3', 0),
  ('dh_go', 'doors', 'From approved preview v3', 0),
  ('dh_h', 'doors', 'From approved preview v3', 0),
  ('dh_p', 'doors', 'From approved preview v3', 0),
  ('doors_h', 'doors', 'From approved preview v3', 0),
  ('doors_k', 'doors', 'From approved preview v3', 0),
  ('download', 'common', 'From UI_Text sheet (Excel)', 0),
  ('download_brochure', 'common', 'From UI_Text sheet (Excel)', 0),
  ('e_choose', 'errors', 'From approved preview v3', 0),
  ('e_email', 'errors', 'From approved preview v3', 0),
  ('e_fill', 'errors', 'From approved preview v3', 0),
  ('e_gst', 'errors', 'From approved preview v3', 0),
  ('e_pick', 'errors', 'From approved preview v3', 0),
  ('e_tel', 'errors', 'From approved preview v3', 0),
  ('email', 'common', 'From UI_Text sheet (Excel)', 0),
  ('eyebrow', 'common', 'From approved preview v3', 0),
  ('f_addr', 'footer', 'From approved preview v3', 0),
  ('f_range', 'footer', 'From approved preview v3', 0),
  ('f_shop', 'footer', 'From approved preview v3', 0),
  ('f_visit', 'footer', 'From approved preview v3', 0),
  ('f_work', 'footer', 'From approved preview v3', 0),
  ('feat_h', 'featured', 'From approved preview v3', 0),
  ('feat_k', 'featured', 'From approved preview v3', 0),
  ('feat_p', 'featured', 'From approved preview v3', 0),
  ('featured_products', 'featured', 'From UI_Text sheet (Excel)', 0),
  ('first_name', 'common', 'From UI_Text sheet (Excel)', 0),
  ('fl_area', 'forms', 'From approved preview v3', 0),
  ('fl_biz', 'forms', 'From approved preview v3', 0),
  ('fl_brands', 'forms', 'From approved preview v3', 0),
  ('fl_firm', 'forms', 'From approved preview v3', 0),
  ('fl_gd', 'forms', 'From approved preview v3', 0),
  ('fl_gst', 'forms', 'From approved preview v3', 0),
  ('fl_msg', 'forms', 'From approved preview v3', 0),
  ('fl_name', 'forms', 'From approved preview v3', 0),
  ('fl_phone', 'forms', 'From approved preview v3', 0),
  ('fl_prod', 'forms', 'From approved preview v3', 0),
  ('fl_qty', 'forms', 'From approved preview v3', 0),
  ('fl_sales', 'forms', 'From approved preview v3', 0),
  ('fl_town', 'forms', 'From approved preview v3', 0),
  ('fl_type', 'forms', 'From approved preview v3', 0),
  ('fo_h', 'try_it', 'From approved preview v3', 0),
  ('fo_k', 'try_it', 'From approved preview v3', 0),
  ('fo_p', 'try_it', 'From approved preview v3', 0),
  ('for_business', 'common', 'From UI_Text sheet (Excel)', 0),
  ('for_home', 'common', 'From UI_Text sheet (Excel)', 0),
  ('hero_l1', 'hero', 'From approved preview v3', 0),
  ('hero_l2', 'hero', 'From approved preview v3', 0),
  ('home_only', 'common', 'From approved preview v3', 0),
  ('kit_cta', 'business', 'From approved preview v3', 0),
  ('know_more', 'common', 'From UI_Text sheet (Excel)', 0),
  ('last_name', 'common', 'From UI_Text sheet (Excel)', 0),
  ('lbl_office', 'common', 'From approved preview v3', 0),
  ('lede', 'common', 'From approved preview v3', 0),
  ('legal1', 'legal', 'From approved preview v3', 0),
  ('legal_privacy_body', 'legal', 'Legal body, English only, HTML; other languages fall back to English', 1),
  ('legal_terms_body', 'legal', 'Legal body, English only, HTML; other languages fall back to English', 1),
  ('lg_en', 'legal', 'From approved preview v3', 0),
  ('lg_priv', 'legal', 'From approved preview v3', 0),
  ('lg_priv_s', 'legal', 'From approved preview v3', 0),
  ('lg_terms', 'legal', 'From approved preview v3', 0),
  ('lg_terms_h', 'legal', 'From approved preview v3', 0),
  ('m_brochure', 'forms', 'From approved preview v3', 0),
  ('m_brochure_s', 'forms', 'From approved preview v3', 0),
  ('m_contact', 'forms', 'From approved preview v3', 0),
  ('m_contact_s', 'forms', 'From approved preview v3', 0),
  ('m_dist', 'forms', 'From approved preview v3', 0),
  ('m_dist_s', 'forms', 'From approved preview v3', 0),
  ('m_quote', 'forms', 'From approved preview v3', 0),
  ('m_quote_s', 'forms', 'From approved preview v3', 0),
  ('mail_bro_intro', 'common', 'From approved preview v3', 0),
  ('mail_bro_subject', 'common', 'From approved preview v3', 0),
  ('map_load', 'common', 'From approved preview v3', 0),
  ('menu', 'common', 'From approved preview v3', 0),
  ('mobile', 'common', 'From UI_Text sheet (Excel)', 0),
  ('msg_btn', 'common', 'From approved preview v3', 0),
  ('n_product', 'common', 'From approved preview v3', 0),
  ('n_products', 'common', 'From approved preview v3', 0),
  ('nav_about', 'nav', 'From approved preview v3', 0),
  ('nav_business', 'nav', 'From approved preview v3', 0),
  ('nav_contact', 'nav', 'From approved preview v3', 0),
  ('nav_products', 'nav', 'From approved preview v3', 0),
  ('nav_where', 'nav', 'From approved preview v3', 0),
  ('none', 'common', 'From approved preview v3', 0),
  ('ok_bro', 'forms', 'From approved preview v3', 0),
  ('ok_other', 'forms', 'From approved preview v3', 0),
  ('optional', 'common', 'From approved preview v3', 0),
  ('pack', 'common', 'From UI_Text sheet (Excel)', 0),
  ('product_id', 'common', 'From UI_Text sheet (Excel)', 0),
  ('range_h', 'range', 'From approved preview v3', 0),
  ('range_k', 'range', 'From approved preview v3', 0),
  ('range_p', 'range', 'From approved preview v3', 0),
  ('request_quote', 'common', 'From UI_Text sheet (Excel)', 0),
  ('ring_hint', 'range', 'From approved preview v3', 0),
  ('rl_fits', 'try_it', 'From approved preview v3', 0),
  ('rl_perf', 'try_it', 'From approved preview v3', 0),
  ('rl_ply', 'try_it', 'From approved preview v3', 0),
  ('rl_pulls', 'try_it', 'From approved preview v3', 0),
  ('rl_soft', 'try_it', 'From approved preview v3', 0),
  ('rl_tear', 'try_it', 'From approved preview v3', 0),
  ('sample', 'common', 'From approved preview v3', 0),
  ('search', 'common', 'From approved preview v3', 0),
  ('see_all_products', 'common', 'From UI_Text sheet (Excel)', 0),
  ('send', 'common', 'From approved preview v3', 0),
  ('specifications', 'common', 'From UI_Text sheet (Excel)', 0),
  ('st_c', 'hero', 'From approved preview v3', 0),
  ('st_l', 'hero', 'From approved preview v3', 0),
  ('st_p', 'hero', 'From approved preview v3', 0),
  ('st_t', 'hero', 'From approved preview v3', 0),
  ('submit', 'common', 'From approved preview v3', 0),
  ('tagline', 'common', 'From UI_Text sheet (Excel)', 0),
  ('thanks', 'common', 'From approved preview v3', 0),
  ('touch', 'common', 'From approved preview v3', 0),
  ('tryit', 'common', 'From approved preview v3', 0),
  ('ur_h', 'try_it', 'From approved preview v3', 0),
  ('ur_k', 'try_it', 'From approved preview v3', 0),
  ('ur_p', 'try_it', 'From approved preview v3', 0),
  ('wa_general', 'common', 'From approved preview v3', 0),
  ('wa_kit', 'common', 'From approved preview v3', 0),
  ('whatsapp_us', 'common', 'From UI_Text sheet (Excel)', 0),
  ('where_h', 'where', 'From approved preview v3', 0),
  ('where_k', 'where', 'From approved preview v3', 0),
  ('where_p', 'where', 'From approved preview v3', 0);

INSERT INTO ui_text (text_key, lang_code, value) VALUES
  ('ab1_h', 'en', 'Our promise'),
  ('ab1_h', 'ta', 'எங்கள் உறுதி'),
  ('ab1_h', 'hi', 'हमारा वादा'),
  ('ab1_p', 'en', 'Paper that feels gentle, packed fresh and priced fairly for the people who use it every day.'),
  ('ab1_p', 'ta', 'மென்மையான காகிதம், புதிதாக பேக் செய்யப்பட்டது, தினமும் பயன்படுத்துபவர்களுக்கு நியாயமான விலையில்.'),
  ('ab1_p', 'hi', 'कोमल पेपर, ताज़ा पैक किया हुआ, और रोज़ इस्तेमाल करने वालों के लिए सही दाम पर।'),
  ('ab2_h', 'en', 'Kanchipuram godown'),
  ('ab2_h', 'ta', 'காஞ்சிபுரம் கிடங்கு'),
  ('ab2_h', 'hi', 'कांचीपुरम गोदाम'),
  ('ab2_p', 'en', 'Stock for all 25 products is held in Kanchipuram and delivered on our own sales beats.'),
  ('ab2_p', 'ta', 'அனைத்து 25 பொருட்களின் இருப்பும் காஞ்சிபுரத்தில் வைக்கப்பட்டு எங்கள் விற்பனை வழித்தடங்களில் விநியோகிக்கப்படுகிறது.'),
  ('ab2_p', 'hi', 'सभी 25 उत्पादों का स्टॉक कांचीपुरम में रहता है और हमारे अपने सेल्स रूट पर डिलीवर होता है।'),
  ('ab3_h', 'en', 'Quality check'),
  ('ab3_h', 'ta', 'தரச் சோதனை'),
  ('ab3_h', 'hi', 'गुणवत्ता जाँच'),
  ('ab3_p', 'en', 'Every lot is checked against its specification before it leaves the godown. If anything is not right, tell us on WhatsApp and our team will follow up.'),
  ('ab3_p', 'ta', 'ஒவ்வொரு தொகுப்பும் கிடங்கிலிருந்து வெளியேறும் முன் அதன் விவரக்குறிப்புடன் சரிபார்க்கப்படுகிறது. ஏதேனும் சரியில்லை என்றால் வாட்ஸ்அப்பில் சொல்லுங்கள், எங்கள் குழு கவனிக்கும்.'),
  ('ab3_p', 'hi', 'हर लॉट गोदाम से निकलने से पहले उसकी विशेषताओं के अनुसार जाँचा जाता है। कुछ भी ठीक न हो तो व्हाट्सऐप पर बताएँ, हमारी टीम देखेगी।'),
  ('ab_h', 'en', 'A gentle brand from Kanchipuram.'),
  ('ab_h', 'ta', 'காஞ்சிபுரத்திலிருந்து ஒரு மென்மையான பிராண்ட்.'),
  ('ab_h', 'hi', 'कांचीपुरम का एक कोमल ब्रांड।'),
  ('ab_k', 'en', 'About us'),
  ('ab_k', 'ta', 'எங்களைப் பற்றி'),
  ('ab_k', 'hi', 'हमारे बारे में'),
  ('ab_p', 'en', 'dFresh is a tissue and hygiene paper brand of Dolluz Corporation (OPC) Pvt Ltd. From our godown in Kanchipuram we supply homes, shops, hotels, restaurants, offices and hospitals across the Kanchipuram, Vellore and Chennai region.'),
  ('ab_p', 'ta', 'dFresh என்பது டோலஸ் கார்ப்பரேஷன் (OPC) பிரைவேட் லிமிடெட்டின் டிஷ்யூ மற்றும் சுகாதாரக் காகித பிராண்ட். காஞ்சிபுரத்தில் உள்ள எங்கள் கிடங்கிலிருந்து காஞ்சிபுரம், வேலூர், சென்னை பகுதி முழுவதும் வீடுகள், கடைகள், ஹோட்டல்கள், உணவகங்கள், அலுவலகங்கள் மற்றும் மருத்துவமனைகளுக்கு விநியோகம் செய்கிறோம்.'),
  ('ab_p', 'hi', 'dFresh, डोलज़ कॉर्पोरेशन (OPC) प्राइवेट लिमिटेड का टिशू और हाइजीन पेपर ब्रांड है। कांचीपुरम में अपने गोदाम से हम कांचीपुरम, वेल्लोर और चेन्नई क्षेत्र के घरों, दुकानों, होटलों, रेस्टोरेंट, ऑफ़िस और अस्पतालों को सप्लाई करते हैं।'),
  ('all', 'en', 'All'),
  ('all', 'ta', 'அனைத்தும்'),
  ('all', 'hi', 'सभी'),
  ('all_h', 'en', 'All products'),
  ('all_h', 'ta', 'அனைத்து தயாரிப்புகள்'),
  ('all_h', 'hi', 'सभी उत्पाद'),
  ('back', 'en', 'Back'),
  ('back', 'ta', 'பின் செல்ல'),
  ('back', 'hi', 'वापस'),
  ('band_h', 'en', 'Let''s talk fresh.'),
  ('band_h', 'ta', 'ஃப்ரெஷ்ஷாகப் பேசுவோம்.'),
  ('band_h', 'hi', 'चलिए फ़्रेश बात करें।'),
  ('band_p', 'en', 'Prices, samples or a distributor partnership. Send us a WhatsApp message and our team will reply.'),
  ('band_p', 'ta', 'விலை, மாதிரி அல்லது விநியோகக் கூட்டாண்மை. WhatsApp-இல் செய்தி அனுப்புங்கள், எங்கள் குழு பதில் அளிக்கும்.'),
  ('band_p', 'hi', 'दाम, सैंपल या वितरक साझेदारी। हमें WhatsApp पर संदेश भेजें, हमारी टीम जवाब देगी।'),
  ('become_distributor', 'en', 'Become a distributor'),
  ('become_distributor', 'ta', 'விநியோகஸ்தர் ஆக'),
  ('become_distributor', 'hi', 'डिस्ट्रीब्यूटर बनें'),
  ('best_for', 'en', 'Best for'),
  ('best_for', 'ta', 'யாருக்கு ஏற்றது'),
  ('best_for', 'hi', 'किसके लिए उपयुक्त'),
  ('biz_h', 'en', 'Built for your business'),
  ('biz_h', 'ta', 'உங்கள் வணிகத்துக்காக'),
  ('biz_h', 'hi', 'आपके व्यवसाय के लिए'),
  ('biz_p', 'en', 'Hover or tap an industry to open its kit.'),
  ('biz_p', 'ta', 'கிட்டைத் திறக்க தொழிலைத் தட்டுங்கள்.'),
  ('biz_p', 'hi', 'किट खोलने के लिए उद्योग पर टैप करें।'),
  ('brand_line', 'en', 'dFresh is a brand of Dolluz Corporation (OPC) Pvt Ltd'),
  ('brand_line', 'ta', 'dFresh என்பது டோலஸ் கார்ப்பரேஷன் (OPC) பிரைவேட் லிமிடெட்டின் பிராண்ட்'),
  ('brand_line', 'hi', 'dFresh, डोलज़ कॉर्पोरेशन (OPC) प्राइवेट लिमिटेड का ब्रांड है'),
  ('bro_pending', 'en', 'Our brochure is being finalised. We have saved your details and will e-mail it to you as soon as it is ready.'),
  ('bro_pending', 'ta', 'எங்கள் பிரோஷர் இறுதி செய்யப்பட்டு வருகிறது. உங்கள் விவரங்களைச் சேமித்துள்ளோம், தயாரானதும் மின்னஞ்சலில் அனுப்புவோம்.'),
  ('bro_pending', 'hi', 'हमारा ब्रोशर तैयार हो रहा है। हमने आपकी जानकारी सहेज ली है और तैयार होते ही इसे ईमेल करेंगे।'),
  ('brochure', 'en', 'Brochure'),
  ('brochure', 'ta', 'கையேடு'),
  ('brochure', 'hi', 'ब्रोशर'),
  ('c_godown', 'en', 'Kanchipuram godown'),
  ('c_godown', 'ta', 'காஞ்சிபுரம் கிடங்கு'),
  ('c_godown', 'hi', 'कांचीपुरम गोदाम'),
  ('c_godown_a', 'en', 'Kanchipuram, Tamil Nadu'),
  ('c_godown_a', 'ta', 'காஞ்சிபுரம், தமிழ்நாடு'),
  ('c_godown_a', 'hi', 'कांचीपुरम, तमिलनाडु'),
  ('c_map', 'en', 'Open in Google Maps'),
  ('c_map', 'ta', 'Google Maps-இல் திறக்க'),
  ('c_map', 'hi', 'Google Maps में खोलें'),
  ('c_office', 'en', 'Padur office'),
  ('c_office', 'ta', 'படூர் அலுவலகம்'),
  ('c_office', 'hi', 'पडूर ऑफ़िस'),
  ('c_office_a', 'en', 'Padur, Chennai, Tamil Nadu'),
  ('c_office_a', 'ta', 'படூர், சென்னை, தமிழ்நாடு'),
  ('c_office_a', 'hi', 'पडूर, चेन्नई, तमिलनाडु'),
  ('choose', 'en', 'Choose…'),
  ('choose', 'ta', 'தேர்ந்தெடுக்கவும்…'),
  ('choose', 'hi', 'चुनें…'),
  ('close', 'en', 'Close'),
  ('close', 'ta', 'மூடு'),
  ('close', 'hi', 'बंद करें'),
  ('colour', 'en', 'Colour'),
  ('colour', 'ta', 'நிறம்'),
  ('colour', 'hi', 'रंग'),
  ('consent', 'en', 'I agree to be contacted by dFresh about my enquiry.'),
  ('consent', 'ta', 'என் விசாரணை தொடர்பாக dFresh என்னைத் தொடர்புகொள்ள ஒப்புக்கொள்கிறேன்.'),
  ('consent', 'hi', 'मैं अपनी पूछताछ के बारे में dFresh द्वारा संपर्क किए जाने के लिए सहमत हूँ।'),
  ('db_go', 'en', 'See business kits'),
  ('db_go', 'ta', 'வணிக கிட்களைப் பார்க்க'),
  ('db_go', 'hi', 'बिज़नेस किट देखें'),
  ('db_h', 'en', 'One quote for your whole kit'),
  ('db_h', 'ta', 'உங்கள் முழுத் தேவைக்கும் ஒரே விலைப்பட்டியல்'),
  ('db_h', 'hi', 'पूरी किट के लिए एक कोटेशन'),
  ('db_p', 'en', 'Hotels, restaurants, offices, factories and hospitals. Ask for a free sample.'),
  ('db_p', 'ta', 'ஹோட்டல்கள், உணவகங்கள், அலுவலகங்கள், தொழிற்சாலைகள், மருத்துவமனைகள். இலவச மாதிரி கேளுங்கள்.'),
  ('db_p', 'hi', 'होटल, रेस्टोरेंट, ऑफ़िस, फ़ैक्टरी और अस्पताल। मुफ़्त सैंपल माँगें।'),
  ('dh_go', 'en', 'Browse home products'),
  ('dh_go', 'ta', 'வீட்டுப் பொருட்களைப் பார்க்க'),
  ('dh_go', 'hi', 'घरेलू उत्पाद देखें'),
  ('dh_h', 'en', 'Everyday softness for the family'),
  ('dh_h', 'ta', 'குடும்பத்துக்கு தினசரி மென்மை'),
  ('dh_h', 'hi', 'परिवार के लिए रोज़ की कोमलता'),
  ('dh_p', 'en', 'Facial tissue, kitchen towels, toilet rolls and napkins for your home.'),
  ('dh_p', 'ta', 'உங்கள் வீட்டுக்கு ஃபேஷியல் டிஷ்யூ, கிச்சன் டவல், டாய்லெட் ரோல் மற்றும் நாப்கின்கள்.'),
  ('dh_p', 'hi', 'आपके घर के लिए फ़ेशियल टिश्यू, किचन टॉवल, टॉयलेट रोल और नैपकिन।'),
  ('doors_h', 'en', 'Made for home. Built for business.'),
  ('doors_h', 'ta', 'வீட்டுக்காக உருவானது. வணிகத்துக்காக கட்டமைக்கப்பட்டது.'),
  ('doors_h', 'hi', 'घर के लिए बना। व्यवसाय के लिए तैयार।'),
  ('doors_k', 'en', 'Who it''s for'),
  ('doors_k', 'ta', 'யாருக்காக'),
  ('doors_k', 'hi', 'किसके लिए'),
  ('download', 'en', 'Download'),
  ('download', 'ta', 'பதிவிறக்கு'),
  ('download', 'hi', 'डाउनलोड करें'),
  ('download_brochure', 'en', 'Download brochure'),
  ('download_brochure', 'ta', 'பிரோஷரைப் பதிவிறக்க'),
  ('download_brochure', 'hi', 'ब्रोशर डाउनलोड करें'),
  ('e_choose', 'en', 'Choose an option.'),
  ('e_choose', 'ta', 'ஒன்றைத் தேர்ந்தெடுக்கவும்.'),
  ('e_choose', 'hi', 'एक विकल्प चुनें।'),
  ('e_email', 'en', 'Enter an e-mail like name@company.com.'),
  ('e_email', 'ta', 'name@company.com போன்ற மின்னஞ்சலை உள்ளிடவும்.'),
  ('e_email', 'hi', 'name@company.com जैसा ईमेल डालें।'),
  ('e_fill', 'en', 'Fill in this field.'),
  ('e_fill', 'ta', 'இதை நிரப்பவும்.'),
  ('e_fill', 'hi', 'कृपया इसे भरें।'),
  ('e_gst', 'en', 'GST numbers have 15 characters, like 33ABCDE1234F1Z5.'),
  ('e_gst', 'ta', 'GST எண் 15 எழுத்துகள் கொண்டது, எ.கா. 33ABCDE1234F1Z5.'),
  ('e_gst', 'hi', 'GST नंबर 15 अक्षरों का होता है, जैसे 33ABCDE1234F1Z5।'),
  ('e_pick', 'en', 'Pick at least one product.'),
  ('e_pick', 'ta', 'குறைந்தது ஒரு பொருளைத் தேர்ந்தெடுக்கவும்.'),
  ('e_pick', 'hi', 'कम से कम एक उत्पाद चुनें।'),
  ('e_tel', 'en', 'Enter a 10-digit Indian mobile starting with 6, 7, 8 or 9.'),
  ('e_tel', 'ta', '6, 7, 8 அல்லது 9-ல் தொடங்கும் 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.'),
  ('e_tel', 'hi', '6, 7, 8 या 9 से शुरू होने वाला 10 अंकों का मोबाइल नंबर डालें।'),
  ('email', 'en', 'E-mail'),
  ('email', 'ta', 'மின்னஞ்சல்'),
  ('email', 'hi', 'ईमेल'),
  ('eyebrow', 'en', 'Tissue & hygiene paper · Kanchipuram'),
  ('eyebrow', 'ta', 'டிஷ்யூ & சுகாதார காகிதம் · காஞ்சிபுரம்'),
  ('eyebrow', 'hi', 'टिश्यू और हाइजीन पेपर · कांचीपुरम'),
  ('f_addr', 'en', 'Padur office · Kanchipuram godown'),
  ('f_addr', 'ta', 'படூர் அலுவலகம் · காஞ்சிபுரம் கிடங்கு'),
  ('f_addr', 'hi', 'पडूर ऑफ़िस · कांचीपुरम गोदाम'),
  ('f_range', 'en', 'Our range'),
  ('f_range', 'ta', 'எங்கள் வகைகள்'),
  ('f_range', 'hi', 'हमारी रेंज'),
  ('f_shop', 'en', 'Shop'),
  ('f_shop', 'ta', 'பொருட்கள்'),
  ('f_shop', 'hi', 'खरीदारी'),
  ('f_visit', 'en', 'Visit'),
  ('f_visit', 'ta', 'முகவரி'),
  ('f_visit', 'hi', 'पता'),
  ('f_work', 'en', 'Work with us'),
  ('f_work', 'ta', 'எங்களுடன் இணையுங்கள்'),
  ('f_work', 'hi', 'हमारे साथ काम करें'),
  ('feat_h', 'en', 'Most loved'),
  ('feat_h', 'ta', 'அதிகம் விரும்பப்படுபவை'),
  ('feat_h', 'hi', 'सबसे पसंदीदा'),
  ('feat_k', 'en', 'Bestsellers'),
  ('feat_k', 'ta', 'அதிகம் விற்பனையாகும்'),
  ('feat_k', 'hi', 'सबसे ज़्यादा बिकने वाले'),
  ('feat_p', 'en', 'Tap "Know more" on any card for sizes, pack and who it suits.'),
  ('feat_p', 'ta', 'அளவு, பேக் மற்றும் யாருக்கு ஏற்றது என அறிய எந்த கார்டிலும் "மேலும் அறிய" தட்டுங்கள்.'),
  ('feat_p', 'hi', 'साइज़, पैक और किसके लिए सही है, जानने के लिए किसी भी कार्ड पर "और जानें" दबाएँ।'),
  ('featured_products', 'en', 'Featured products'),
  ('featured_products', 'ta', 'சிறப்புப் பொருட்கள்'),
  ('featured_products', 'hi', 'चुनिंदा उत्पाद'),
  ('first_name', 'en', 'First name'),
  ('first_name', 'ta', 'முதல் பெயர்'),
  ('first_name', 'hi', 'पहला नाम'),
  ('fl_area', 'en', 'Town & areas covered'),
  ('fl_area', 'ta', 'ஊர் & பகுதிகள்'),
  ('fl_area', 'hi', 'शहर और क्षेत्र'),
  ('fl_biz', 'en', 'Business name'),
  ('fl_biz', 'ta', 'நிறுவனத்தின் பெயர்'),
  ('fl_biz', 'hi', 'व्यवसाय का नाम'),
  ('fl_brands', 'en', 'Brands handled now'),
  ('fl_brands', 'ta', 'தற்போது கையாளும் பிராண்டுகள்'),
  ('fl_brands', 'hi', 'अभी संभाले जा रहे ब्रांड'),
  ('fl_firm', 'en', 'Firm name'),
  ('fl_firm', 'ta', 'நிறுவனப் பெயர்'),
  ('fl_firm', 'hi', 'फ़र्म का नाम'),
  ('fl_gd', 'en', 'Godown / vehicles'),
  ('fl_gd', 'ta', 'கிடங்கு / வாகனங்கள்'),
  ('fl_gd', 'hi', 'गोदाम / वाहन'),
  ('fl_gst', 'en', 'GST no.'),
  ('fl_gst', 'ta', 'GST எண்'),
  ('fl_gst', 'hi', 'GST नंबर'),
  ('fl_msg', 'en', 'Message'),
  ('fl_msg', 'ta', 'செய்தி'),
  ('fl_msg', 'hi', 'संदेश'),
  ('fl_name', 'en', 'Name'),
  ('fl_name', 'ta', 'பெயர்'),
  ('fl_name', 'hi', 'नाम'),
  ('fl_phone', 'en', 'Phone (WhatsApp)'),
  ('fl_phone', 'ta', 'தொலைபேசி (WhatsApp)'),
  ('fl_phone', 'hi', 'फ़ोन (WhatsApp)'),
  ('fl_prod', 'en', 'Products'),
  ('fl_prod', 'ta', 'தயாரிப்புகள்'),
  ('fl_prod', 'hi', 'उत्पाद'),
  ('fl_qty', 'en', 'Monthly quantity'),
  ('fl_qty', 'ta', 'மாதாந்திர அளவு'),
  ('fl_qty', 'hi', 'मासिक मात्रा'),
  ('fl_sales', 'en', 'Monthly tissue sales'),
  ('fl_sales', 'ta', 'மாதாந்திர டிஷ்யூ விற்பனை'),
  ('fl_sales', 'hi', 'मासिक टिश्यू बिक्री'),
  ('fl_town', 'en', 'Town'),
  ('fl_town', 'ta', 'ஊர்'),
  ('fl_town', 'hi', 'शहर'),
  ('fl_type', 'en', 'Business type'),
  ('fl_type', 'ta', 'தொழில் வகை'),
  ('fl_type', 'hi', 'व्यवसाय का प्रकार'),
  ('fo_h', 'en', 'Pick a size.'),
  ('fo_h', 'ta', 'அளவைத் தேர்ந்தெடுங்கள்.'),
  ('fo_h', 'hi', 'आकार चुनिए।'),
  ('fo_k', 'en', 'The napkin'),
  ('fo_k', 'ta', 'நாப்கின்'),
  ('fo_k', 'hi', 'नैपकिन'),
  ('fo_p', 'en', 'Watch it unfold.'),
  ('fo_p', 'ta', 'அது விரிவதைப் பாருங்கள்.'),
  ('fo_p', 'hi', 'इसे खुलते देखिए।'),
  ('for_business', 'en', 'For Business'),
  ('for_business', 'ta', 'வணிகத்துக்கு'),
  ('for_business', 'hi', 'व्यवसाय के लिए'),
  ('for_home', 'en', 'For Home'),
  ('for_home', 'ta', 'வீட்டுக்கு'),
  ('for_home', 'hi', 'घर के लिए'),
  ('hero_l1', 'en', 'Gentle,'),
  ('hero_l1', 'ta', 'உங்களைப் போலவே'),
  ('hero_l1', 'hi', 'आपकी तरह'),
  ('hero_l2', 'en', 'like you.'),
  ('hero_l2', 'ta', 'மென்மையானது.'),
  ('hero_l2', 'hi', 'कोमल।'),
  ('home_only', 'en', 'For Home'),
  ('home_only', 'ta', 'வீட்டுக்கு'),
  ('home_only', 'hi', 'घर के लिए'),
  ('kit_cta', 'en', 'Request this kit'),
  ('kit_cta', 'ta', 'இந்த கிட்டைக் கேட்க'),
  ('kit_cta', 'hi', 'यह किट मंगाएँ'),
  ('know_more', 'en', 'Know more'),
  ('know_more', 'ta', 'மேலும் அறிய'),
  ('know_more', 'hi', 'और जानें'),
  ('last_name', 'en', 'Last name'),
  ('last_name', 'ta', 'கடைசிப் பெயர்'),
  ('last_name', 'hi', 'अंतिम नाम'),
  ('lbl_office', 'en', 'Office'),
  ('lbl_office', 'ta', 'அலுவலகம்'),
  ('lbl_office', 'hi', 'ऑफ़िस'),
  ('lede', 'en', 'Napkins, rolls, towels, facial tissue and wet wipes for homes, hotels, restaurants, offices and hospitals. A premium brand at a fair, local price.'),
  ('lede', 'ta', 'வீடுகள், ஹோட்டல்கள், உணவகங்கள், அலுவலகங்கள், மருத்துவமனைகளுக்கு நாப்கின்கள், ரோல்கள், டவல்கள், ஃபேஷியல் டிஷ்யூ மற்றும் வெட் வைப்ஸ். நியாயமான உள்ளூர் விலையில் பிரீமியம் பிராண்ட்.'),
  ('lede', 'hi', 'घरों, होटलों, रेस्टोरेंट, ऑफ़िस और अस्पतालों के लिए नैपकिन, रोल, टॉवल, फ़ेशियल टिश्यू और वेट वाइप्स। उचित स्थानीय दाम पर प्रीमियम ब्रांड।'),
  ('legal1', 'en', 'Dolluz Corporation (OPC) Pvt Ltd · CIN U72501TN2018OPC120419 · GSTIN to be confirmed'),
  ('legal1', 'ta', 'டோலஸ் கார்ப்பரேஷன் (OPC) பிரைவேட் லிமிடெட் · CIN U72501TN2018OPC120419 · GSTIN விரைவில்'),
  ('legal1', 'hi', 'डोलज़ कॉर्पोरेशन (OPC) प्राइवेट लिमिटेड · CIN U72501TN2018OPC120419 · GSTIN जल्द'),
  ('legal_privacy_body', 'en', '<p>This policy explains how Dolluz Corporation (OPC) Pvt Ltd ("Dolluz", "we") handles personal data collected through the dFresh website, in line with the Digital Personal Data Protection Act, 2023.</p><h4>What we collect</h4><ul><li>Brochure download: first name, last name, e-mail and mobile number.</li><li>Quote and sample requests: name, business name and type, town, phone, e-mail, products, quantity and message.</li><li>Distributor applications: name, firm name, GST number, areas covered, godown and vehicle details, brands handled, sales range, phone and e-mail.</li><li>Messages sent through the contact form.</li><li>Website usage through Google Analytics (pages viewed, buttons clicked). No payment data is collected.</li></ul><h4>Why we use it</h4><p>Only to reply to your enquiry, send the brochure and product information, and follow up on quotes, samples and distributor applications. We record your consent on every form.</p><h4>Sharing</h4><p>We do not sell your data. It is stored with our service providers (website hosting, e-mail and Google Workspace) only to run the services above.</p><h4>Your rights</h4><p>You can ask to see, correct or delete your data, or withdraw consent, by writing to info@dolluzcorp.com. We keep enquiry data only as long as needed to serve you and meet legal requirements.</p><h4>Contact</h4><p>Dolluz Corporation (OPC) Pvt Ltd, Padur, Chennai, Tamil Nadu. E-mail info@dolluzcorp.com. Phone +91 77790 39666.</p>'),
  ('legal_terms_body', 'en', '<p>dFresh is a brand of Dolluz Corporation (OPC) Pvt Ltd. By using this website you agree to these terms.</p><h4>Product information</h4><p>Product photos and specifications are for reference. Final specifications, prices and minimum order quantities are confirmed in our written quote.</p><h4>No online sales</h4><p>This website is a catalogue. Prices are shared on request, and orders are confirmed by our team by phone, WhatsApp or e-mail.</p><h4>Content</h4><p>All text, images and the dFresh logo belong to Dolluz Corporation (OPC) Pvt Ltd and may not be copied or reused without written permission.</p><h4>Marketed by</h4><p>Dolluz Corporation (OPC) Pvt Ltd · CIN U72501TN2018OPC120419 · Padur office · Kanchipuram godown.</p>'),
  ('lg_en', 'en', ''),
  ('lg_en', 'ta', 'சட்ட உரை ஆங்கிலத்தில் மட்டுமே உள்ளது.'),
  ('lg_en', 'hi', 'कानूनी पाठ केवल अंग्रेज़ी में है।'),
  ('lg_priv', 'en', 'Privacy policy (DPDP Act 2023)'),
  ('lg_priv', 'ta', 'தனியுரிமைக் கொள்கை (DPDP சட்டம் 2023)'),
  ('lg_priv', 'hi', 'गोपनीयता नीति (DPDP अधिनियम 2023)'),
  ('lg_priv_s', 'en', 'Privacy policy'),
  ('lg_priv_s', 'ta', 'தனியுரிமைக் கொள்கை'),
  ('lg_priv_s', 'hi', 'गोपनीयता नीति'),
  ('lg_terms', 'en', 'Terms'),
  ('lg_terms', 'ta', 'விதிமுறைகள்'),
  ('lg_terms', 'hi', 'शर्तें'),
  ('lg_terms_h', 'en', 'Terms of use'),
  ('lg_terms_h', 'ta', 'பயன்பாட்டு விதிமுறைகள்'),
  ('lg_terms_h', 'hi', 'उपयोग की शर्तें'),
  ('m_brochure', 'en', 'Get the dFresh brochure'),
  ('m_brochure', 'ta', 'dFresh கையேட்டைப் பெறுங்கள்'),
  ('m_brochure', 'hi', 'dFresh ब्रोशर पाएँ'),
  ('m_brochure_s', 'en', 'All 25 products, sizes and pack options in one PDF.'),
  ('m_brochure_s', 'ta', 'அனைத்து 25 தயாரிப்புகள், அளவுகள், பேக் விருப்பங்கள் ஒரே PDF-இல்.'),
  ('m_brochure_s', 'hi', 'सभी 25 उत्पाद, साइज़ और पैक विकल्प एक PDF में।'),
  ('m_contact', 'en', 'Send us a message'),
  ('m_contact', 'ta', 'எங்களுக்கு செய்தி அனுப்புங்கள்'),
  ('m_contact', 'hi', 'हमें संदेश भेजें'),
  ('m_contact_s', 'en', 'Questions, feedback or anything else. We reply on WhatsApp or e-mail.'),
  ('m_contact_s', 'ta', 'கேள்விகள், கருத்துகள் அல்லது வேறு எதுவும். வாட்ஸ்அப் அல்லது மின்னஞ்சலில் பதிலளிப்போம்.'),
  ('m_contact_s', 'hi', 'सवाल, सुझाव या कुछ और। हम व्हाट्सऐप या ईमेल पर जवाब देंगे।'),
  ('m_dist', 'en', 'Become a dFresh distributor'),
  ('m_dist', 'ta', 'dFresh விநியோகஸ்தர் ஆகுங்கள்'),
  ('m_dist', 'hi', 'dFresh वितरक बनें'),
  ('m_dist_s', 'en', 'For towns outside our own sales beats.'),
  ('m_dist_s', 'ta', 'எங்கள் விற்பனைப் பாதைக்கு வெளியே உள்ள ஊர்களுக்கு.'),
  ('m_dist_s', 'hi', 'हमारे सेल्स रूट से बाहर के शहरों के लिए।'),
  ('m_quote', 'en', 'Request a quote or free sample'),
  ('m_quote', 'ta', 'விலைப்பட்டியல் அல்லது இலவச மாதிரி கேளுங்கள்'),
  ('m_quote', 'hi', 'कोटेशन या मुफ़्त सैंपल माँगें'),
  ('m_quote_s', 'en', 'Tell us what you need. We will send prices and a sample kit.'),
  ('m_quote_s', 'ta', 'உங்களுக்கு என்ன தேவை என்று சொல்லுங்கள். விலையும் மாதிரி கிட்டும் அனுப்புவோம்.'),
  ('m_quote_s', 'hi', 'बताइए आपको क्या चाहिए। हम दाम और सैंपल किट भेजेंगे।'),
  ('mail_bro_intro', 'en', 'Hi {name}, thank you for your interest in dFresh. Download the brochure with the link below (valid for 7 days). For prices and samples, reply on WhatsApp +91 93302 59330.'),
  ('mail_bro_intro', 'ta', 'வணக்கம் {name}, dFresh மீது ஆர்வம் காட்டியதற்கு நன்றி. கீழே உள்ள இணைப்பில் பிரோஷரைப் பதிவிறக்கவும் (7 நாட்கள் செல்லுபடியாகும்). விலை மற்றும் மாதிரிகளுக்கு வாட்ஸ்அப் +91 93302 59330.'),
  ('mail_bro_intro', 'hi', 'नमस्ते {name}, dFresh में रुचि के लिए धन्यवाद। नीचे दिए लिंक से ब्रोशर डाउनलोड करें (7 दिन तक मान्य)। दाम और सैंपल के लिए व्हाट्सऐप +91 93302 59330.'),
  ('mail_bro_subject', 'en', 'Your dFresh brochure'),
  ('mail_bro_subject', 'ta', 'உங்கள் dFresh பிரோஷர்'),
  ('mail_bro_subject', 'hi', 'आपका dFresh ब्रोशर'),
  ('map_load', 'en', 'Map loads when you are online'),
  ('map_load', 'ta', 'இணையத்தில் இருக்கும்போது வரைபடம் தோன்றும்'),
  ('map_load', 'hi', 'ऑनलाइन होने पर नक्शा दिखेगा'),
  ('menu', 'en', 'Menu'),
  ('menu', 'ta', 'மெனு'),
  ('menu', 'hi', 'मेनू'),
  ('mobile', 'en', 'Mobile number'),
  ('mobile', 'ta', 'மொபைல் எண்'),
  ('mobile', 'hi', 'मोबाइल नंबर'),
  ('msg_btn', 'en', 'Send us a message'),
  ('msg_btn', 'ta', 'எங்களுக்கு செய்தி அனுப்புங்கள்'),
  ('msg_btn', 'hi', 'हमें संदेश भेजें'),
  ('n_product', 'en', '{n} product'),
  ('n_product', 'ta', '{n} தயாரிப்பு'),
  ('n_product', 'hi', '{n} उत्पाद'),
  ('n_products', 'en', '{n} products'),
  ('n_products', 'ta', '{n} தயாரிப்புகள்'),
  ('n_products', 'hi', '{n} उत्पाद'),
  ('nav_about', 'en', 'About'),
  ('nav_about', 'ta', 'எங்களைப் பற்றி'),
  ('nav_about', 'hi', 'हमारे बारे में'),
  ('nav_business', 'en', 'For Business'),
  ('nav_business', 'ta', 'வணிகங்களுக்கு'),
  ('nav_business', 'hi', 'व्यवसायों के लिए'),
  ('nav_contact', 'en', 'Contact'),
  ('nav_contact', 'ta', 'தொடர்பு'),
  ('nav_contact', 'hi', 'संपर्क'),
  ('nav_products', 'en', 'Products'),
  ('nav_products', 'ta', 'தயாரிப்புகள்'),
  ('nav_products', 'hi', 'उत्पाद'),
  ('nav_where', 'en', 'Where to buy'),
  ('nav_where', 'ta', 'எங்கே வாங்குவது'),
  ('nav_where', 'hi', 'कहाँ से खरीदें'),
  ('none', 'en', 'No product matches that search. Try a size like 30×30 or an ID like DF037.'),
  ('none', 'ta', 'அந்தத் தேடலுக்கு பொருந்தும் தயாரிப்பு இல்லை. 30×30 போன்ற அளவு அல்லது DF037 போன்ற ID-ஐ முயற்சிக்கவும்.'),
  ('none', 'hi', 'इस खोज से कोई उत्पाद मेल नहीं खाता। 30×30 जैसा साइज़ या DF037 जैसी ID आज़माएँ।'),
  ('ok_bro', 'en', 'On the live site the brochure PDF downloads now and a copy goes to your e-mail.'),
  ('ok_bro', 'ta', 'நேரடி தளத்தில் பிரோஷர் PDF இப்போதே பதிவிறங்கும், ஒரு நகல் உங்கள் மின்னஞ்சலுக்கும் வரும்.'),
  ('ok_bro', 'hi', 'लाइव साइट पर ब्रोशर PDF अभी डाउनलोड होगा और एक कॉपी आपके ईमेल पर जाएगी।'),
  ('ok_other', 'en', 'Our team will contact you on WhatsApp.'),
  ('ok_other', 'ta', 'எங்கள் குழு வாட்ஸ்அப்பில் உங்களைத் தொடர்புகொள்ளும்.'),
  ('ok_other', 'hi', 'हमारी टीम आपसे व्हाट्सऐप पर संपर्क करेगी।'),
  ('optional', 'en', 'optional'),
  ('optional', 'ta', 'விருப்பம்'),
  ('optional', 'hi', 'वैकल्पिक'),
  ('pack', 'en', 'Pack'),
  ('pack', 'ta', 'பேக்'),
  ('pack', 'hi', 'पैक'),
  ('product_id', 'en', 'Product ID'),
  ('product_id', 'ta', 'பொருள் ID'),
  ('product_id', 'hi', 'उत्पाद ID'),
  ('range_h', 'en', 'Six ways to soft'),
  ('range_h', 'ta', 'மென்மையின் ஆறு வழிகள்'),
  ('range_h', 'hi', 'मुलायम के छह रूप'),
  ('range_k', 'en', 'Spin the range'),
  ('range_k', 'ta', 'வரிசையைச் சுழற்றுங்கள்'),
  ('range_k', 'hi', 'रेंज घुमाइए'),
  ('range_p', 'en', 'Drag to spin. Tap a category to open it.'),
  ('range_p', 'ta', 'சுழற்ற இழுக்கவும். திறக்க தட்டவும்.'),
  ('range_p', 'hi', 'घुमाने के लिए खींचें। खोलने के लिए टैप करें।'),
  ('request_quote', 'en', 'Request a quote'),
  ('request_quote', 'ta', 'விலைப்பட்டியல் கேட்க'),
  ('request_quote', 'hi', 'कोटेशन मांगें'),
  ('ring_hint', 'en', 'Drag to spin'),
  ('ring_hint', 'ta', 'சுழற்ற இழுக்கவும்'),
  ('ring_hint', 'hi', 'घुमाने के लिए खींचें'),
  ('rl_fits', 'en', 'FITS EVERY HOLDER'),
  ('rl_fits', 'ta', 'எல்லா ஹோல்டரிலும் பொருந்தும்'),
  ('rl_fits', 'hi', 'हर होल्डर में फ़िट'),
  ('rl_perf', 'en', 'PERFORATED'),
  ('rl_perf', 'ta', 'துளையிடப்பட்டது'),
  ('rl_perf', 'hi', 'छिद्रित'),
  ('rl_ply', 'en', '2-PLY'),
  ('rl_ply', 'ta', '2-ப்ளை'),
  ('rl_ply', 'hi', '2-प्लाई'),
  ('rl_pulls', 'en', '~300 PULLS'),
  ('rl_pulls', 'ta', '~300 இழுப்புகள்'),
  ('rl_pulls', 'hi', '~300 पुल'),
  ('rl_soft', 'en', 'SOFT'),
  ('rl_soft', 'ta', 'மென்மை'),
  ('rl_soft', 'hi', 'मुलायम'),
  ('rl_tear', 'en', 'CLEAN TEAR'),
  ('rl_tear', 'ta', 'சுத்தமாகக் கிழியும்'),
  ('rl_tear', 'hi', 'साफ़ फटता है'),
  ('sample', 'en', 'Get a free sample'),
  ('sample', 'ta', 'இலவச மாதிரி பெற'),
  ('sample', 'hi', 'मुफ़्त सैंपल पाएँ'),
  ('search', 'en', 'Search by name or ID'),
  ('search', 'ta', 'பெயர் அல்லது ID மூலம் தேடுங்கள்'),
  ('search', 'hi', 'नाम या ID से खोजें'),
  ('see_all_products', 'en', 'See all products'),
  ('see_all_products', 'ta', 'அனைத்து பொருட்களையும் காண'),
  ('see_all_products', 'hi', 'सभी उत्पाद देखें'),
  ('send', 'en', 'Send request'),
  ('send', 'ta', 'கோரிக்கையை அனுப்பு'),
  ('send', 'hi', 'अनुरोध भेजें'),
  ('specifications', 'en', 'Specifications'),
  ('specifications', 'ta', 'விவரக்குறிப்புகள்'),
  ('specifications', 'hi', 'विशेषताएँ'),
  ('st_c', 'en', 'categories'),
  ('st_c', 'ta', 'வகைகள்'),
  ('st_c', 'hi', 'श्रेणियाँ'),
  ('st_l', 'en', 'languages'),
  ('st_l', 'ta', 'மொழிகள்'),
  ('st_l', 'hi', 'भाषाएँ'),
  ('st_p', 'en', 'products'),
  ('st_p', 'ta', 'தயாரிப்புகள்'),
  ('st_p', 'hi', 'उत्पाद'),
  ('st_t', 'en', 'towns served'),
  ('st_t', 'ta', 'ஊர்கள்'),
  ('st_t', 'hi', 'शहर'),
  ('submit', 'en', 'Submit'),
  ('submit', 'ta', 'சமர்ப்பி'),
  ('submit', 'hi', 'जमा करें'),
  ('tagline', 'en', 'Gentle, Like You'),
  ('tagline', 'ta', 'உங்களைப் போலவே மென்மையானது'),
  ('tagline', 'hi', 'आपकी तरह कोमल'),
  ('thanks', 'en', 'Thank you'),
  ('thanks', 'ta', 'நன்றி'),
  ('thanks', 'hi', 'धन्यवाद'),
  ('touch', 'en', 'Touch the tissue'),
  ('touch', 'ta', 'டிஷ்யூவைத் தொடுங்கள்'),
  ('touch', 'hi', 'टिश्यू को छुएँ'),
  ('tryit', 'en', 'Try it'),
  ('tryit', 'ta', 'முயற்சிக்கவும்'),
  ('tryit', 'hi', 'आज़माइए'),
  ('ur_h', 'en', 'Roll it out.'),
  ('ur_h', 'ta', 'விரித்துப் பாருங்கள்.'),
  ('ur_h', 'hi', 'खोलकर देखिए।'),
  ('ur_k', 'en', 'The roll'),
  ('ur_k', 'ta', 'ரோல்'),
  ('ur_k', 'hi', 'रोल'),
  ('ur_p', 'en', 'Spin the roll to let the paper out, spin it back to wind it up. Or just pull the paper.'),
  ('ur_p', 'ta', 'காகிதத்தை விரிக்க ரோலைச் சுழற்றுங்கள், மீண்டும் சுருட்ட எதிர்த்திசையில் சுழற்றுங்கள். அல்லது காகிதத்தை இழுக்கவும்.'),
  ('ur_p', 'hi', 'कागज़ खोलने के लिए रोल घुमाएँ, वापस लपेटने के लिए उल्टा घुमाएँ। या बस कागज़ खींचें।'),
  ('wa_general', 'en', 'Hi dFresh, I''d like to know more about your products.'),
  ('wa_general', 'ta', 'வணக்கம் dFresh, உங்கள் பொருட்களைப் பற்றி மேலும் அறிய விரும்புகிறேன்.'),
  ('wa_general', 'hi', 'नमस्ते dFresh, मैं आपके उत्पादों के बारे में और जानना चाहता/चाहती हूँ।'),
  ('wa_kit', 'en', 'Hi dFresh, please send a quote for the {kit} kit: {items}.'),
  ('wa_kit', 'ta', 'வணக்கம் dFresh, {kit} கிட்டுக்கான விலைப்பட்டியலை அனுப்புங்கள்: {items}.'),
  ('wa_kit', 'hi', 'नमस्ते dFresh, कृपया {kit} किट का कोटेशन भेजें: {items}।'),
  ('whatsapp_us', 'en', 'WhatsApp us'),
  ('whatsapp_us', 'ta', 'வாட்ஸ்அப்பில் தொடர்பு கொள்ள'),
  ('whatsapp_us', 'hi', 'व्हाट्सऐप करें'),
  ('where_h', 'en', 'From our godown to your door.'),
  ('where_h', 'ta', 'எங்கள் கிடங்கிலிருந்து உங்கள் வாசலுக்கு.'),
  ('where_h', 'hi', 'हमारे गोदाम से आपके दरवाज़े तक।'),
  ('where_k', 'en', 'Where we deliver'),
  ('where_k', 'ta', 'நாங்கள் டெலிவரி செய்யும் இடங்கள்'),
  ('where_k', 'hi', 'हम कहाँ डिलीवर करते हैं'),
  ('where_p', 'en', 'Stock ships from Kanchipuram to six towns on our own sales beats. Outside these towns? Become a distributor.'),
  ('where_p', 'ta', 'காஞ்சிபுரத்திலிருந்து எங்கள் விற்பனைப் பாதையிலுள்ள ஆறு ஊர்களுக்கு சரக்கு அனுப்பப்படுகிறது. இந்த ஊர்களுக்கு வெளியே இருக்கிறீர்களா? விநியோகஸ்தர் ஆகுங்கள்.'),
  ('where_p', 'hi', 'कांचीपुरम से हमारे अपने सेल्स रूट के छह शहरों तक माल जाता है। इन शहरों से बाहर हैं? वितरक बनें।');

INSERT INTO site_settings (setting_key, setting_value, is_public, description) VALUES
  ('whatsapp_number', '919330259330', 1, 'wa.me number, digits only'),
  ('whatsapp_display', '+91 93302 59330', 1, 'shown on the site'),
  ('office_phone', '+91 77790 39666', 1, 'shown on the site'),
  ('lead_email', 'info@dolluzcorp.com', 0, 'every lead is e-mailed here'),
  ('public_email', 'info@dolluzcorp.com', 1, 'shown on the site'),
  ('mail_from', '"dFresh" <connect@dolluzcorp.com>', 0, 'must be a verified SendGrid sender'),
  ('company_name', 'Dolluz Corporation (OPC) Pvt Ltd', 1, 'legal name'),
  ('cin', 'U72501TN2018OPC120419', 1, 'footer'),
  ('gstin', '', 1, 'TO BE PROVIDED - footer shows "to be confirmed" while empty'),
  ('office_address', 'Padur, Chennai, Tamil Nadu', 1, 'TO CONFIRM exact address'),
  ('godown_address', 'Kanchipuram, Tamil Nadu', 1, 'TO CONFIRM exact address'),
  ('office_map_query', 'Padur, Chennai, Tamil Nadu', 1, 'Google Maps query or place id'),
  ('godown_map_query', 'Kanchipuram, Tamil Nadu', 1, 'Google Maps query or place id'),
  ('ga4_measurement_id', '', 1, 'TO BE PROVIDED, e.g. G-XXXXXXX'),
  ('gsheet_spreadsheet_id', '', 0, 'TO BE PROVIDED - lead sheet (tabs per form)'),
  ('recaptcha_site_key', '', 1, 'optional - honeypot + rate limit are always on'),
  ('site_url', 'https://dfresh.in', 1, 'TO CONFIRM domain (brief: dfresh.com is not owned)');

INSERT INTO admin_users (emp_id, role, is_active, created_by) VALUES
  ('DZIND002', 'admin', 1, 'seed'),
  ('DZIND148', 'admin', 1, 'seed');

SET FOREIGN_KEY_CHECKS = 1;
