// `npm run fonts:build`: self-hosted web fonts (woff2, font-display: swap), generated from the DB, committed.
// Run it after adding a language, changing a languages.font_family, or adding text with characters a script
// font has not seen yet (a missing character falls back to the next font in the stack, it never disappears).
// - Brand display font (Saira) and the DEFAULT language's font: Google's latin + latin-ext files (all their
//   characters), variable weight 300-800.
// - Every other language's font: ONE variable file (300-800) subset to the characters that language's content
//   uses (bootstrap + legal pages + the language list), Google Fonts `text=` subsetting, which keeps the
//   shaping rules for those characters.
// - Language switch labels: a tiny weight-600 subset per font with just the labels, family "dFresh label <font>"
//   (src/i18n/fonts.js labelFamily), so the switch shows every script without loading that script's font.
// Output: src/fonts/*.woff2 (webpack fingerprints them into /static/media), src/styles/fonts.css (@font-face),
// src/i18n/selfHostedFonts.json (what is self-hosted; fonts.js asks Google only for anything else, e.g. a new
// language before this ran; preload = the Latin files the first screen uses, linked by scripts/prerender.js).
// Languages are data: nothing here names a language.
require('dotenv').config({ quiet: true });

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FONTS = path.join(ROOT, 'src/fonts');
const CSS = path.join(ROOT, 'src/styles/fonts.css');
const JSON_OUT = path.join(ROOT, 'src/i18n/selfHostedFonts.json');
const BRAND = 'Saira';
const WEIGHTS = '300..800';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36';

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const plus = (family) => family.trim().replace(/ +/g, '+');

async function get(url, as = 'text') {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  return as === 'buffer' ? Buffer.from(await res.arrayBuffer()) : res.text();
}

// [{ comment, weight, url, range }] from Google's css2 answer.
function faces(css) {
  const out = [];
  const re = /(?:\/\*\s*([\w-]+)\s*\*\/\s*)?@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(css))) {
    const body = m[2];
    out.push({
      comment: m[1] || '',
      weight: (/font-weight:\s*([^;]+);/.exec(body) || [])[1],
      url: (/src:\s*url\(([^)]+)\)/.exec(body) || [])[1],
      range: (/unicode-range:\s*([^;]+);/.exec(body) || [])[1],
    });
  }
  return out;
}

const written = new Set();
async function save(name, url) {
  const buf = await get(url, 'buffer');
  fs.writeFileSync(path.join(FONTS, name), buf);
  written.add(name);
  return buf.length;
}

function rule(family, weight, file, range) {
  return `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n`
    + `  src: url(../fonts/${file}) format('woff2');\n${range ? `  unicode-range: ${range};\n` : ''}}\n`;
}

// Google's latin + latin-ext files of a family (all characters of those ranges).
async function latinFamily(family, report) {
  const css = await get(`https://fonts.googleapis.com/css2?family=${plus(family)}:wght@${WEIGHTS}&display=swap`);
  let out = '';
  for (const f of faces(css).filter((x) => ['latin', 'latin-ext'].includes(x.comment))) {
    const file = `${slug(family)}-${f.comment}.woff2`;
    report.push([file, await save(file, f.url)]);
    out += rule(family, f.weight, file, f.range);
  }
  if (!out) throw new Error(`no latin files for ${family}`);
  return out;
}

// One file with exactly the characters in text (Google `text=` subsetting, unicode-range included).
async function subsetFamily(family, text, weights, cssFamily, file, report) {
  const chars = [...new Set([...text])].filter((c) => c.trim()).sort().join('');
  const css = await get(`https://fonts.googleapis.com/css2?family=${plus(family)}:wght@${weights}&text=${encodeURIComponent(chars)}&display=swap`);
  const [f] = faces(css);
  if (!f || !f.url) throw new Error(`no subset for ${family}`);
  report.push([file, await save(file, f.url), [...chars].length]);
  return rule(cssFamily, f.weight, file, f.range);
}

async function main() {
  const { content } = require('../src/backend_routes/Public_server');
  const langs = (await content.loadLanguages()).data;
  const def = langs.languages.find((l) => l.code === langs.default);
  if (!def || !def.fontFamily) throw new Error('the default language has no font_family');

  fs.mkdirSync(FONTS, { recursive: true });
  const report = [];
  let css = `/* GENERATED by \`npm run fonts:build\` (scripts/fonts-build.js) from the languages table: do not edit. */\n`;
  const families = [BRAND, def.fontFamily];
  css += await latinFamily(BRAND, report);
  if (def.fontFamily !== BRAND) css += await latinFamily(def.fontFamily, report);

  // Script fonts: characters of everything that language shows.
  const byFont = new Map();
  for (const l of langs.languages) {
    if (!l.fontFamily || families.includes(l.fontFamily)) continue;
    const boot = (await content.getBootstrap(l.code)).data;
    const legal = [];
    for (const page of ['privacy', 'terms']) {
      try { legal.push((await content.getLegal(page, l.code)).data); } catch { /* no legal page: nothing to add */ }
    }
    byFont.set(l.fontFamily, (byFont.get(l.fontFamily) || '') + JSON.stringify([boot, legal, langs]));
  }
  for (const [family, text] of byFont) {
    families.push(family);
    css += await subsetFamily(family, text, WEIGHTS, family, `${slug(family)}-content.woff2`, report);
  }

  // Switch labels, every font.
  const labels = {};
  for (const l of langs.languages) {
    if (!l.fontFamily) continue;
    labels[l.fontFamily] = (labels[l.fontFamily] || '') + l.switchLabel;
  }
  for (const [family, text] of Object.entries(labels)) {
    css += await subsetFamily(family, text, '600', `dFresh label ${family}`, `label-${slug(family)}.woff2`, report);
    labels[family] = [...new Set([...text])].join('');
  }

  for (const f of fs.readdirSync(FONTS)) if (f.endsWith('.woff2') && !written.has(f)) fs.unlinkSync(path.join(FONTS, f));
  fs.writeFileSync(CSS, css);
  fs.writeFileSync(JSON_OUT, `${JSON.stringify({
    families,
    labels,
    preload: [`${slug(BRAND)}-latin.woff2`, `${slug(def.fontFamily)}-latin.woff2`],
  }, null, 2)}\n`);
  for (const [file, bytes, n] of report) console.log(`  ${file.padEnd(36)} ${String(Math.round(bytes / 102.4) / 10).padStart(6)} KB${n ? `  (${n} characters)` : ''}`);
  console.log(`fonts: ${report.length} files in src/fonts, src/styles/fonts.css, src/i18n/selfHostedFonts.json`);
  process.exit(0);
}

main().catch((err) => {
  console.error('fonts:build failed:', err.message);
  process.exit(1);
});
